### ISSUE TITLE
url_for missing for some links

### ISSUE THREAD

**Issue by wraythex** [Map-A-Droid/MAD#1003]
There are several places where previous url_for links have now been hard coded, causing them to fail for some users.  Thanks to CypherChris, it looks like PR986 may be the reason I see this issue on my server.  I'm using nginx and have a sub-path for my url, like `https://web.url/mad/status` etc.  I just did a git pull and restart within the past hour.

One example is that the loading.gif animated logo now shows as a broken link.
Instead of `url_for('static', filename='loading.gif') }}`
The code has several places where it is hard coded: `static/loading.gif`

Also, when I click the Apply Settings button, I see the broken loading.gif image for a long time, and then it times-out giving the following error:
`https://web.url/mad/reload`
`504 Gateway Time-out`

Watching the server console, it looks like the Apply Settings button actually does trigger the apply settings action but it never goes back to a use-able web page on its own.  I have to manually navigate back to one of my MADmin pages.

Please let me know if you need any more information.

**Comment by sn0opy** [comment]
@wraythex have a look at #1050.

```
git fetch origin
git checkout -b fix-loading-overlay origin/fix-loading-overlay
git merge master
```

**Comment by wraythex** [comment]
I ran:
```
git fetch origin
git checkout -b fix-loading-overlay origin/fix-loading-overlay
```
git branch shows:
```
* fix-loading-overlay
  master
```
When I click apply settings I now see the animated gif.  I am also returned to a use-able madmin page.  I tried this from several different madmin pages and it always worked.  Thanks for this update!
