### ISSUE TITLE
Auto-Config Case Sensitivity

### ISSUE THREAD

**Issue by Seandals** [Map-A-Droid/MAD#1005]
Hey there. While flashing my boxes tonight to x64 I ran into some issues due to the MAD Backend username login in PogoDroid being case sensitive but in the Auto-Config PogoDroid Configuration options it defaults all inputs to lowercase, causing logins to fail. Can this field be changed to respect character case as entered?

**Comment by Expl0dingBanana** [comment]
This was fixed in d85881d5c2b5b74787e2386b78569a4b8a177f6c. What commit hash are you currently on?

**Comment by Seandals** [comment]
> This was fixed in [d85881d](https://github.com/Map-A-Droid/MAD/commit/d85881d5c2b5b74787e2386b78569a4b8a177f6c). What commit hash are you currently on?

I pull every night at midnight. Still defaults to lowercase on current master.

**Comment by krzee** [comment]
banana, it was google that needed to be all lowercase... i didnt know the MAD backend is case sensitive for emails... but if it is then then it needs to be handled differently from google email

**Comment by krzee** [comment]
or maybe the right solution is to make the backend not be case sensitive for emails, as email addresses should not be case sensitive in the first place
