### ISSUE TITLE
PoGo Auth not idiot proof

### ISSUE THREAD

**Issue by dkmur** [Map-A-Droid/MAD#1013]
When copy and paste a password into PoGo Auth and by accident leaving a whitespace at the end then apparently the device won't login, surprisingly 😇

**Comment by sn0opy** [comment]
What is the expected change for this? Sometimes, passwords are allowed to contain whitespaces. Not sure if it's a good idea, to remove them.

**Comment by dkmur** [comment]
I do not expect anything, I point out whenever I run into an issue and leave it to people that actually have a brain to decide what to do with the information provided.
