### ISSUE TITLE
Changes to existing area not reflected in MADmin

### ISSUE THREAD

**Issue by dkmur** [Map-A-Droid/MAD#102]
Within an existing Area I just changed my geofence and routecalc (to scan a bigger area for quests), MAD created new route.calc, MADmin on the other hand is still showing the old route, from last night which does not reflect the changes made.

Next I’ve created a new Area, including the geofence and routecalc from the old area, to avoid a recalc, that new area isn’t shown in MADmin at all.

Finally delete route calc in new Area and have it recalculated calculate by MAD (restarted MAD), then both area as the new route.calc are shown in sidebar.

Nothing shocking, just fyi.

**Comment by michikrug** [comment]
Madmin only reads the info when it's started. I introduced a change in my geofences PR that reloads the info when you edit your mappings.

**Comment by sn0opy** [comment]
Guess this should be fixed, since information is read directly from memory now.
