### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement opencv-python<4.3,>=4.1 

### ISSUE THREAD

**Issue by rushi12565** [Map-A-Droid/MAD#1076]
I got this error while installing the requirements

Collecting mysqlclient~=1.4
  Using cached mysqlclient-1.4.6.tar.gz (85 kB)
ERROR: Could not find a version that satisfies the requirement opencv-python<4.3,>=4.1 (from -r requirements.txt (line 14)) (from versions: 3.4.10.37, 3.4.11.39, 3.4.11.41, 3.4.11.43, 3.4.11.45, 4.3.0.38, 4.4.0.40, 4.4.0.42, 4.4.0.44, 4.4.0.46)
ERROR: No matching distribution found for opencv-python<4.3,>=4.1 (from -r requirements.txt (line 14))

**Comment by sn0opy** [comment]
Read the readme. You most certainly run Python 3.9 which is not yet supported by MAD. 

You can install other Python verisons along each other.

**Comment by rushi12565** [comment]
> Read the readme. You most certainly run Python 3.9 which is not yet supported by MAD. 
> 
> You can install other Python verisons along each other.

no my python version 3.8.5
is that not supported too
sorry if I'm just dumb

**Comment by rushi12565** [comment]
@sn0opy

**Comment by sn0opy** [comment]
If you're installing on a RaspberryPi, you're probably out of luck as well. Python 3.8.6 is still working fine on standard Linux systems.
