### ISSUE TITLE
MADmin: Doesent save password correctly if using numbers only

### ISSUE THREAD

**Issue by fremel75** [Map-A-Droid/MAD#108]
I noted a small bug: if you use only numbers in password under AUTH it writes the password without "" in mappings.json

**Comment by Expl0dingBanana** [comment]
This should be resolved with #383 / #390

**Comment by Expl0dingBanana** [comment]
This issue can be resolved with #411 into master

**Comment by sn0opy** [comment]
Fixed, as #411 has been merged.
