### ISSUE TITLE
virtual env

### ISSUE THREAD

**Issue by rushi12565** [Map-A-Droid/MAD#1087]
I might be just dumb but I want to know,

Is it mandatory to install MAD in virtual environment otlr we can install it normally too

**Comment by muckelba** [comment]
I thought i've added a line to the docs saying something like "A venv is not necessary but quite useful".

So: no, its not mandatory but if you wanna setup RocketMAD as well you might wanna setup either of those with an venv.

**Comment by rushi12565** [comment]
oh my bad😅😅
Thanks for the info

**Comment by mag3sticl** [comment]
You don’t need a virtual environment for either. I have most adding installed without ever needing to use one. Most, if not all work with latest python 🐍

**Comment by rushi12565** [comment]
@mag3sticl thats good to hear😄
