### ISSUE TITLE
error while installing requirements (trying on ubuntu in termux) 

### ISSUE THREAD

**Issue by rushi12565** [Map-A-Droid/MAD#1088]
So, I was trying to see if I can run MAD on ubuntu which is installed on termux (I was just curious 😅). I know that there is no where noted that MAD works on ubuntu in termux or it might actually not work(or am I just dumb and miss it somewhere??) but still I couldn't stop my curiosity so help me if anyone can... 
and while installing requirements I got an error while matplotlib was installing

This is the image showing the error
![2021-1-7_8-59-20](https://user-images.githubusercontent.com/74148058/103848885-6f3f4c80-50c9-11eb-871e-9250f88c4732.PNG)

**Comment by JabLuszko** [comment]
Hey,

First of all GitHub is not an help 'channel' - it would be total mess if everyone will come here with every bit of problem - please use discord for that. Please stop posting screenshots of text - those are not searchable/indexable. Text is a text, for a reason.

Also your log says check the logs for full command output, have you checked the logs?
