### ISSUE TITLE
dockerhub updating issue

### ISSUE THREAD

**Issue by trilispy** [Map-A-Droid/MAD#1110]
dockerhub hasn't been automatically been updating on push to master for the last 14 days now. I have seen there been lots of merges to master in this time. I have no idea if this is a known issue. I did try check the discord server first and there no open issue on github regarding this.

**Comment by Expl0dingBanana** [comment]
I have asked Grenn to look into this tomorrow. Thanks for letting us know!

**Comment by Breee** [comment]
> dockerhub hasn't been automatically been updating on push to master for the last 14 days now. I have seen there been lots of merges to master in this time. I have no idea if this is a known issue. I did try check the discord server first and there no open issue on github regarding this.

In the meantime use  `docker build -t  mapadroid/map-a-droid .`

@Grennith if you need assistance just hmu

**Comment by sn0opy** [comment]
It's not a Docker issue. The issue is actually due to MAD's dependencies being broken. Banana and I were already looking into it. Fix is on the way

**Comment by Expl0dingBanana** [comment]
This issue has been "resolved". I have uploaded the old version of TextWizard to pypi to allow pip to work its magic.

![image](https://user-images.githubusercontent.com/13160095/109250780-40378400-77b8-11eb-97df-af262d05a453.png)
