### ISSUE TITLE
Settings Devices - add pause/start to bulk update

### ISSUE THREAD

**Issue by Axiangel** [Map-A-Droid/MAD#1196]
It's quite tedious to pause / start several devices at once (for example when you are getting PTC ban limits). There are two dialogue popups where an "OK" i needed to change status for each device. Sometimes they also need a few seconds to pup up, so 3 clicks per device to pause / start.

Ideally, i would like to use the bulk update function to select all, hit pause, and then unpause them like 10 at a time to avoid PTC ban limits.
Would this be possible please?

**Comment by muckelba** [comment]
While this is not possible with the GUI, use this bash snippet to do it:
```bash
while read p; do
        curl -u user:pass "http://localhost:5000${p}" -H "Content-Type: application/json-rpc" --data-binary '{"call":"device_state","args":{"active":0}}'
done < <(curl -s -u user:pass http://localhost:5000/api/device | jq --raw-output ".results | keys | .[]")
```
