### ISSUE TITLE
Delete lucky eggs if account is > lvl 30

### ISSUE THREAD

**Issue by t00fan** [Map-A-Droid/MAD#121]
If the scanning account is lvl 30 or above, then it should be ok to delete the lucky eggs from the bag as well.  Sometimes it's causing problems because it can't delete other items (for lack of seeing it on one screen because of Lucky Eggs, Camera, Raid Pass and Gifts).

**Comment by cecpk** [comment]
thats not a issue. do not get it adjusted - if the box is full, then there should be enough to delete there. but you can send me pictures and a log - then I'll take a look
