### ISSUE TITLE
New Pogodroid quest problem

### ISSUE THREAD

**Issue by cyphercris** [Map-A-Droid/MAD#127]
After update Pogodroid to new version, quest scanning is not working.

**Comment by krzee** [comment]
itrack reported the fix in #english about 6 hours ago


iTrack      Yesterday at 5:41 PM
Quick Fix for Questscanning. Credits to @pki :

            log.info('Spin Stop')
            self._spin_wheel(2)
            data_received = self._wait_for_data(timestamp=self._stop_process_time, proto_to_wait_for=101, timeout=20)
            if data_received is not None:

                if 'Box' in data_received:
                    self._communicator.backButton()
                    log.error('Box is full ... Next round!')
                    self.clear_thread_task = 1
                    break

                if 'Quest' in data_received:
                    self._communicator.backButton()
                    log.info('Getting new Quest')
                    self.clear_thread_task = 2
                    break

worker/WorkerQuests.py, starting at line 331
