### ISSUE TITLE
Not receiving all the gym updates (rmWrapper) as webhooks

### ISSUE THREAD

**Issue by JabLuszko** [Map-A-Droid/MAD#147]
No idea if this problem applies to mono, not even looking there.
No idea if this problem applies to other webhooks types, just migrating, this one was broken :)

Webhook worker is trying to detect changed gyms with last_modified field and 10 seconds sleep using time.time().
rmWrapper fills last_modified field in DB as the last_modified_timestamp_ms field from POGO protos (https://github.com/Map-A-Droid/MAD/blob/master/db/rmWrapper.py#L790).

Situation:

Someone put pokemon in gym / change gym color at 20:00:00, my worker goes there 20:00:44, and let's say process GMO at 20:00:45 and in the same second sleep ends for webhook worker.

last_modified in DB will be set to 20:00:00, but because it's currently 20:00:45 the earlier changes detected by 10 seconds sleeping webhook worker will be AFTER 20:00:35 - ergo we will never get those gym changes. Not this run, not next run, never. It looks like actual gym changes must happen within 10 seconds to be processed by webhook worker.

No idea how you want to approach. The whole idea of having last_modified from actual POGO protos is amazing, but won't work this way.

**Comment by sn0opy** [comment]
Good find! So, instead we could switch back to last_scanned, which might become a bit spammy tho. The only alternative would be a seperate kind of cache that holds everything that has been sent. 

Pro: duplicate sending is finally killed
Contract: higher memory use or higher load due to more DB queries.

**Comment by pkiel** [comment]
Had the same problem with Pokemon and raids.

Why not subtract 60 or more seconds to all of these timestamps?
https://github.com/Map-A-Droid/MAD/blob/master/db/rmWrapper.py#L1260

`tsdt = datetime.utcfromtimestamp(timestamp-60).strftime("%Y-%m-%d %H:%M:%S")`

Contra: Some double posts
Pro: Not missing any data + resend if webhook server is too busy.

**Comment by sn0opy** [comment]
> Why not subtract 60 or more seconds to all of these timestamps?

Wouldn't you have to substract it by the time it takes to perform one full raid round? Otherwise you would still miss information I think.

**Comment by JabLuszko** [comment]
> Wouldn't you have to substract it by the time it takes to perform one full raid round? Otherwise you would still miss information I think.

Yes, this is my current band aid approach - my round takes like 2-3 minutes, so I ask for last 6 minutes of data. This is valid only for me and only when all phones are up, so not really a valid approach, just a quick-fix.
```self.__db_wrapper.get_gyms_changed_since((self.__last_check-350))```
--
@pkiel said about Pokemons (not using that at all) and Raids (I didn't observe anything problematic there, but did not pay that much attention) and 60 seconds is working for him so I have a feeling his issue is different. Raids uses last_scanned and now as in
``` now = datetime.utcfromtimestamp(time.time()).strftime("%Y-%m-%d %H:%M:%S") ``` so the times are relative - it's using MAD time to insert and MAD time to query for changes. Maybe he has a big queue/slow MySQL/not enough workers and it takes longer than 10 seconds to actually insert data into db?
