### ISSUE TITLE
raid ocr scanning, ongoing raid (without egg) doesn't scan time left

### ISSUE THREAD

**Issue by markterantula** [Map-A-Droid/MAD#162]
When a raid is found in the "raid boss" state ("MonWithoutEgg" it's called in the code if I'm not mistaken), the OCR tries to scan "Ongoing", and can't get the time from that:

2019-04-11 16:32:44,809 [         Thread-11][    segscanner:65][   DEBUG] [Crop: 1 (1554993164.478644) ] detectRaidTime: detect raidtimer text: 0ng0ing

It should look at the text above that for the real "time left" data.
The result is that "time_end" in the database will be wrong

**Comment by cecpk** [comment]
theres a second check - did you see  it at log? there are two lines. timer and time left
