### ISSUE TITLE
raids ocr scanning, some raids are missing

### ISSUE THREAD

**Issue by cyphercris** [Map-A-Droid/MAD#188]
Some raids in ocr scan is missing. Logs show in some gyms make a crop image and not analyse. Some crop images are empty in temp (event fresh created). And last interesting thing is that, show only gyms and raids (in ocr menu) from area that match with geofence that have the another walker.

**Comment by cyphercris** [comment]
Also how I know in unrecognized gyms match gym works? Choose match gym, but nothing happen.

**Comment by markterantula** [comment]
Do you perhaps have the screenshots leading to the empty crop images?
I had a phone to test this with out of curiosity, but it broke down, so I can't test stuff, but I can add screenshots to my install and see what happens :)

What I did in my local codebase, when I noticed this stuff, is make the minRadius,maxRadius in cv2.HoughCircles a bit more resilient in segscanner and fileObserver, so:

in ocr/segscanner.y line 421: minRadius=radius-1, maxRadius=radius+1
in ocr/fileObserver.py line 58: minRadius = ..... -1, maxRadius = ... +1

Not sure if part of that is merged, should check, but it might help a little

**Comment by cyphercris** [comment]
Thanks its help, but still is some gyms egg or raid it's problem. Can I send you some screenshots and gyms to check where is problem.

**Comment by markterantula** [comment]
I can have a look if you can put the images somewhere (preferably the initial screenshot I guess) and for the gyms the relevant info (name, location, image url, etc)

**Comment by cyphercris** [comment]
Screenshoots upload soon. Its a lot of them 

[gym_img.zip](https://github.com/Map-A-Droid/MAD/files/3186267/gym_img.zip)
[mon_img.zip](https://github.com/Map-A-Droid/MAD/files/3186268/mon_img.zip)
[weather.zip](https://github.com/Map-A-Droid/MAD/files/3186269/weather.zip)
[www_hash.zip](https://github.com/Map-A-Droid/MAD/files/3186270/www_hash.zip)
[gymsql.zip](https://github.com/Map-A-Droid/MAD/files/3186223/gymsql.zip)

**Comment by cyphercris** [comment]
https://mega.nz/#!tGJQSYzY!cKC77R-oWbk-S5ucGO6BVEupvkpQGJPfBlR2ZP0A1BQ

**Comment by cyphercris** [comment]
Support for ocr is end, so close that.
