### ISSUE TITLE
webhook worker is killed by an unhandled exception

### ISSUE THREAD

**Issue by temp666** [Map-A-Droid/MAD#193]
the webhook worker is killed by an unhandled exception:

> [04-28 04:27:50.92] [   webhook_worker] [      dbWrapperBase:124 ] [   ERROR] Failed executing query: 2055: Lost connection to MySQL server at 'xxx.xxx.xxx.xxx:xxxx', system error: 104 Connection reset by peer
[04-28 04:27:52.98] [   webhook_worker] [              start:57  ] [CRITICAL] Unhandled patched exception (<class 'mysql.connector.errors.OperationalError'>): "MySQL Connection not available.".

in this case what a local disconnect (24 hours internet discconect).
The webhook worker only works again when I restart MAD.
Is it possible that the webhook worker continues to run and tries until he can send again without restarting MAD?

**Comment by georgeherby** [comment]
On one of my instances faced this issue, as mentioned a restart solved it.

**Comment by temp666** [comment]
the problem was fixed many commits ago
