### ISSUE TITLE
Redmi 6A quests not deleting

### ISSUE THREAD

**Issue by korentzari** [Map-A-Droid/MAD#212]
Quests never delete  menu quests is open.   Bot not click on trash for delete eache quests

Log with -vvvv and screenshot same time ( get with phonecontrol )

DeviceWidth=720, deviceHeight=1440 ( 2x)
Mode full  immesive activate for pokemon go

> [05-16 13:43:26.10] [clear_thread_redmi6a07] [    WebsocketServer:437 ] [   DEBUG] redmi6a07 sending command: screen capture jpeg 80
> [05-16 13:43:26.10] [clear_thread_redmi6a07] [    WebsocketServer:452 ] [   DEBUG] To be sent: 47;screen capture jpeg 80
> [05-16 13:43:26.10] [clear_thread_redmi6a07] [    WebsocketServer:457 ] [   DEBUG] Timeout: 30
> [05-16 13:43:26.12] [          scanner] [    WebsocketServer:310 ] [   DEBUG] Retrieving next message to send
> [05-16 13:43:26.74] [           system] [              start:141 ] [   DEBUG] Starting internal Cleanup
> [05-16 13:43:26.74] [           system] [              start:142 ] [   DEBUG] Collecting...
> [05-16 13:43:26.76] [           system] [              start:145 ] [   DEBUG] Unreachable objects: 0 - Remaining garbage: [] - Running threads: 26
> [05-16 13:43:26.76] [           system] [              start:154 ] [   DEBUG] Clearing gc garbage
> [05-16 13:43:26.76] [           system] [              start:160 ] [    INFO] Instance Name: "DEV" - Memory usage: 0.13051223754882812 - CPU usage: 73.9
> [05-16 13:43:26.76] [           system] [      dbWrapperBase:1149] [   DEBUG] dbWrapper::insert_usage
> [05-16 13:43:27.75] [          scanner] [    WebsocketServer:391 ] [   DEBUG] Received binary values.
> [05-16 13:43:27.75] [clear_thread_redmi6a07] [    WebsocketServer:459 ] [   DEBUG] Received answer in time, popping response
> [05-16 13:43:27.75] [clear_thread_redmi6a07] [    WebsocketServer:467 ] [   DEBUG] Received binary data to redmi6a07, starting with b'\xff\xd8\xff\xe0\x00\x10JFIF'
> [05-16 13:43:27.76] [clear_thread_redmi6a07] [       communicator:116 ] [   DEBUG] Storing screenshot...
> [05-16 13:43:27.76] [clear_thread_redmi6a07] [       communicator:121 ] [   DEBUG] Done storing, returning
> [05-16 13:43:27.76] [clear_thread_redmi6a07] [         WorkerBase:643 ] [   DEBUG] Success retrieving screenshot
> [05-16 13:43:27.76] [clear_thread_redmi6a07] [         WorkerBase:610 ] [   DEBUG] _get_trash_positions: checking screen
> [05-16 13:43:27.98] [clear_thread_redmi6a07] [           MITMBase:122 ] [    INFO] Found 1 trashcan(s) on screen
> [05-16 13:43:27.98] [clear_thread_redmi6a07] [           MITMBase:128 ] [    INFO] Delete old quest 1
> [05-16 13:43:27.98] [clear_thread_redmi6a07] [    WebsocketServer:437 ] [   DEBUG] redmi6a07 sending command: screen click 624 834
> [05-16 13:43:27.98] [clear_thread_redmi6a07] [    WebsocketServer:452 ] [   DEBUG] To be sent: 48;screen click 624 834
> [05-16 13:43:27.98] [clear_thread_redmi6a07] [    WebsocketServer:457 ] [   DEBUG] Timeout: 30
> [05-16 13:43:28.00] [          scanner] [    WebsocketServer:310 ] [   DEBUG] Retrieving next message to send
> [05-16 13:43:29.58] [          scanner] [    WebsocketServer:386 ] [   DEBUG] Receiving message: 48;OK
> [05-16 13:43:29.58] [clear_thread_redmi6a07] [    WebsocketServer:459 ] [   DEBUG] Received answer in time, popping response
> [05-16 13:43:29.58] [clear_thread_redmi6a07] [    WebsocketServer:464 ] [   DEBUG] Response to redmi6a07: OK
> [05-16 13:43:30.58] [clear_thread_redmi6a07] [    WebsocketServer:437 ] [   DEBUG] redmi6a07 sending command: screen click 360 791
> [05-16 13:43:30.58] [clear_thread_redmi6a07] [    WebsocketServer:452 ] [   DEBUG] To be sent: 49;screen click 360 791
> [05-16 13:43:30.58] [clear_thread_redmi6a07] [    WebsocketServer:457 ] [   DEBUG] Timeout: 30
> [05-16 13:43:30.60] [          scanner] [    WebsocketServer:310 ] [   DEBUG] Retrieving next message to send
> [05-16 13:43:32.36] [          scanner] [    WebsocketServer:386 ] [   DEBUG] Receiving message: 49;OK
> [05-16 13:43:32.36] [clear_thread_redmi6a07] [    WebsocketServer:459 ] [   DEBUG] Received answer in time, popping response
> [05-16 13:43:32.36] [clear_thread_redmi6a07] [    WebsocketServer:464 ] [   DEBUG] Response to redmi6a07: OK
> [05-16 13:43:33.36] [clear_thread_redmi6a07] [    WebsocketServer:437 ] [   DEBUG] redmi6a07 sending command: screen click 360 1344
> [05-16 13:43:33.36] [clear_thread_redmi6a07] [    WebsocketServer:452 ] [   DEBUG] To be sent: 50;screen click 360 1344
> [05-16 13:43:33.36] [clear_thread_redmi6a07] [    WebsocketServer:457 ] [   DEBUG] Timeout: 30
> [05-16 13:43:33.37] [          scanner] [    WebsocketServer:310 ] [   DEBUG] Retrieving next message to send
> [05-16 13:43:35.33] [          scanner] [    WebsocketServer:386 ] [   DEBUG] Receiving message: 50;OK
> [05-16 13:43:35.33] [clear_thread_redmi6a07] [    WebsocketServer:459 ] [   DEBUG] Received answer in time, popping response
> [05-16 13:43:35.33] [clear_thread_redmi6a07] [    WebsocketServer:464 ] [   DEBUG] Response to redmi6a07: OK
> [05-16 13:43:36.83] [clear_thread_redmi6a07] [           MITMBase:140 ] [   DEBUG] {_clear_quests} finished
> 

![screenshot_redmi6a07](https://user-images.githubusercontent.com/45642437/57851517-0ebb1780-77e1-11e9-8c41-37c9e9723fb1.jpg)

**Comment by cyphercris** [comment]
Do you have magisk 19?

**Comment by korentzari** [comment]
19.0 not 19.1.

**Comment by korentzari** [comment]
```
+++ b/ocr/matching_trash.py
@@ -43,7 +43,7 @@ def trash_image_matching(screen_img):
         sc_till = 1
     elif width == 720:
         sc_from = 0.5
-        sc_till = 0.9
+        sc_till = 0.6
     else:
         sc_from = 0.1
         sc_till = 2

```

With partial roolback  on commit  8e62096575b153ebc7e23537cc5732a1b5c1358d
All quest is deleted  .

**Comment by korentzari** [comment]
```
-    if width <= 1080 and width > 720:
+    if width <= 1080 and width >= 720:
```
Work fine also

**Comment by korentzari** [comment]
I have roolback  my bad patche .

And change crible utils/trashcan.png 

![ttrashcanredmi.png](https://user-images.githubusercontent.com/45642437/57881655-2666c000-7822-11e9-8cbb-1ea9bc0e0255.png)

**Comment by cecpk** [comment]
Wtf is going on here? 🤔

**Comment by korentzari** [comment]
After change images utils/trashcan.png 
Quest cleaning working 
Inventory cleaning not working

Why not use https://raw.githubusercontent.com/ZeChrales/PogoAssets/master/static_assets/png/trashcan.png  with transparency

**Comment by m3g4mInD** [comment]
Hi @cecpk  i have same problem with last commits #206 , even sometimes he goes to store & open tabs raids & mons ...... need to  re-check the code thnaks

**Comment by korentzari** [comment]
For me fix is ok for QuestClean and InventoryClean
