### ISSUE TITLE
open gym is not close during pokestops scan.

### ISSUE THREAD

**Issue by korentzari** [Map-A-Droid/MAD#224]
Opened GYM is not detected on mode quest . 

Never test present of cross for close gym.

And after start loop "test turn map , click pokestop" and long time after "pokemon go restart"

Need detect open gym instead of a pokestop or detected cross before turn  ( add proto 156 on wait_proto ).

**Comment by ColdShadow80** [comment]
Yeap. Really needs a fix. Worker somerimes is there for an hour stuck on a gym instead of questing

**Comment by cecpk** [comment]
Pls test again. Thx

**Comment by sn0opy** [comment]
Closed this due to no response.
