### ISSUE TITLE
Find ditto based on weather

### ISSUE THREAD

**Issue by krzee** [Map-A-Droid/MAD#225]
How to Spot a Ditto in the Wild - posted by Boby360

Partly Cloudy – Search for Yanma, Zubat, Gastly and Gulpin. If weather boosted it’s a Ditto.
Rainy – Yanma is boosted in rainy weather. So, during a rainy day, search for Yanma that doesn’t appear as boosted!
Windy – Yanma and Zubat are boosted by windy weather. Be on the lookout for any Yanma or Zubat that is not weather boosted.
Cloudy – Zubat, Gastly and Gulpin are boosted when cloudy. Search for any Zubat, Gastly or Gulpin that doesn’t appear as boosted.
Foggy – Gastly is boosted when cloudy. Seach for one that is not weather boosted.

**Comment by sn0opy** [comment]
Maybe this is something @na-ji could implement into RM? Guess MAD is the wrong place for this.

**Comment by na-ji** [comment]
Good idea! It won't find every dittos, but should be a first

**Comment by krzee** [comment]
i disagree that this belongs on the map. MAD populates the database and sends webhooks of what is out. This makes discovering what is out MAD's job, not the frontend's.

**Comment by sn0opy** [comment]
But MAD cannot update a mon it doesn't see. Let's say the weather changes and the boost status for the mon updates. MAD won't see it, but the frontend dies since it know the cell's weather.

On the other hand: MAD has no use fo such information. Webhooks don't even support this kind of information nor do we show mon on the MADmin map yet.

Adding a "could_be_ditto" collumn makes no sense, since you can easily "calculte" it checking the cell's weather and the mon's boost status on the map.

**Comment by krzee** [comment]
theres absolutely no way the frontend has more data than mad, which gives the data to said frontend

**Comment by sn0opy** [comment]
> theres absolutely no way the frontend has more data than mad, which gives the data to said frontend

kinda correct. But Mad might see the cell's weather from much greater distance, so the map CAN update the mon's "ditto status" based on the cell's weather. MAD won't be able to keep mons updated every second thus even for small areas, it can take up to 15 min to get a mon updated again, but the cell will be kept updated since it has a much bigger radius.

Also: what kind of information should MAD send via the webhook? Should it send a Ditto at coord X/Y? That would be kinda wrong, since people won't see an actual Ditto there.

**Comment by krzee** [comment]
is_ditto=1
im only talking about setting it once, when seen.
you're talking about keeping them updated... thats a different conversation and would be something else entirely... if that were possible it would be super handy for knowing that IV has re-rolled. I understand why that can't really be MAD's job.
However, I also see no reason why seeing that a mon is a ditto at the moment it is encountered would be the frontend's job. That has nothing to do with constantly checking weather. You simply check it at the encounter and done.

**Comment by sn0opy** [comment]
I'm talking about the fact, that it won't be a Ditto anymore, if the weather changes. Duke has a fair point on Discord saying, that we don't care about other mon probably changing due to weather effects as well, so why should we care about it for Dittos then.

I mean, anybody should feel free to send a PR fully supporting this. Which means:

- Monocle support
- RM support
- automated DB schema update

**Comment by krzee** [comment]
i meant the same thing as duke

> you're talking about keeping them updated... thats a different conversation and would be something else entirely... if that were possible it would be super handy for knowing that IV has re-rolled. I understand why that can't really be MAD's job.

we already understand that things re-roll at weather change. why would we treat this so differently?

Earlier you closed this issue without any discussion (after it sat for 2 weeks) saying it did not belong in MAD...
So now you're saying it can go into MAD, but just that you just personally don't care to code it, is that correct?

**Comment by sn0opy** [comment]
> Earlier you closed this issue without any discussion (after it sat for 2 weeks) saying it did not belong in MAD...
> So now you're saying it can go into MAD, but just that you just personally don't care to code it, is that correct?

Basically this. It sat here for 2 weeks without anyone caring about it anyway, so why keep an issue open for longer, if nobody's interested? I'll give it another 2 weeks, before closing it again. Will add it to the wishlist tho.

**Comment by krzee** [comment]
`select` * from pokemon where disappear_time > utc_timestamp() and (pokemon_id in (193, 41, 92, 316) and weather_boosted_condition=3) ;

thats a ditto, but then theres the case of the logic for finding when things are not boosted and should be... less easy via query i guess since i dont see weather cell in pokemon table

**Comment by krzee** [comment]
if we could get a column in the pokemon table which had actual weather and not boost info, we could use that with the boost info to do the rest via query. at that point this is easy to handle outside of mad and could be considered a nonissue. even PA users could use a simple script (which maybe i could write, depending how complex their needs are) to shoot the data to a webhook. i know it would solve things for users of software that queries the database directly

**Comment by sn0opy** [comment]
That collumn would be redundant. Since we know the position of a spawn, we know the L20 cell of it, thus we also know the weather.

**Comment by krzee** [comment]
Awesome, can you please pass a query for any of the other categories of
ditto than the one i posted?

**Comment by SkOODaT** [comment]
can we confirm that this even still works, im hearing varying comments that Niantic changed this a bit back weather can not be used anymore to determinate ditto

**Comment by krzee** [comment]
> can we confirm that this even still works, im hearing varying comments that Niantic changed this a bit back weather can not be used anymore to determinate ditto

Yes. After I made the above query hydrobooster put it in his krzbot instance and found a ditto disguised as a gulpin. apparently he gets a lot of partly cloudy weather

**Comment by tppkgo** [comment]
![image](https://user-images.githubusercontent.com/45214420/60553356-3d5e6480-9d33-11e9-8926-cf7455662e0c.png)

**Comment by Tabbomat** [comment]
I just caught a Ditto disguised as a Gulpin. Partly Cloudy weather, but the Gulpin had no weather boost. App Version 0.149.1. I have video proof, will update this as soon as I find out how to upload to YouTube. 
I guess this means that this method doesn't work? The Ditto was caught far away from any area where mon_iv scanning is currently active, so I can't check the RM db.

**Comment by krzee** [comment]
It works, here's a gulpin ditto from 4 days ago.

**Comment by krzee** [comment]
2 reasons this is ready to be closed:

1. the system has changed (sometime since july 23rd, last time my first query found a mon) and now a ditto advertises boost if his mask should be boosted. that makes the entire OP invalid.

2. PMSF has implemented the query Sk00dat mentioned, there is now ditto detection in PMSF as sn00py was saying it should be. This whole thread is moot.
