### ISSUE TITLE
RemoteGPSController Issue

### ISSUE THREAD

**Issue by acocalypso** [Map-A-Droid/MAD#259]
After installing and systemizing the app I granted permissions for gps and storage, then I said something is using app overlay, but not sure what to disable here.

Then I stuck at Waiting for permissions screen.

Edit: I'm using a Oneplus2

**Comment by krzee** [comment]
make sure it has su root permissions in magisk
make sure it has all permissions that it wants in android settings - apps - remotegpscontroller

Please continue this in discord if needed

**Comment by Grennith** [comment]
Use terminal systemizer magisk Module to systemize
