### ISSUE TITLE
MADmin geofence editor coordinates go out of bounds.

### ISSUE THREAD

**Issue by sebastienvercammen** [Map-A-Droid/MAD#329]
When using MADmin's map to draw a geofence, if you've scrolled past the bounds of the original world, the saved coordinates will be beyond the bounds of the real world, causing the route/position generation to go beyond the geofence and map the world.

**Environment:**
* `dev` branch, latest commit (https://github.com/Map-A-Droid/MAD/commit/0d97dc25f9680b75cf1821dc96ff17511319e37a)
* py3.7
* Raspbian Buster

**To fix:**
Modulo. Keep coordinates within bounds.
_(Keep in mind the difference between remainder [= JS' modulo] and [least positive residue](https://en.wikipedia.org/wiki/Modulo_operation#Remainder_calculation_for_the_modulo_operation) [= python's modulo].)_

**Steps to reproduce:**
1. Open MADmin's map.
2. To make things easier/quicker, zoom all the way out till you see the world multiple times. _(Step can be omitted.)_
3. Move the map beyond the bounds of the original world.
4. Draw a geofence in any world that is not the very first one.
5. Save the geofence.

The saved geofence will have coordinates within the bounds of the world you drew it in, beyond the bounds of the first world.

The problem: When generating the route (positions), it will try to generate routes to map the world several times, going beyond the geofence. No error message or crash, just stuck generating positions.

**Comment by fosJoddie** [comment]
I got the fix for this, will PR as soon as I get the time
