### ISSUE TITLE
MADmin status "Last date/time of data" never gets filled.

### ISSUE THREAD

**Issue by sebastienvercammen** [Map-A-Droid/MAD#330]
On MADmin's status page, the column _"Last date/time of data"_ never gets filled.

![image](https://user-images.githubusercontent.com/4874269/63131506-3bd4bd00-bfbe-11e9-9650-c80f93afebb3.png)

Mapping works, column stays empty:
* PogoDroid and RGC are working properly on the ATV.
* PogoDroid shows last data sent timestamp on the ATV.
* Phone is walking/scanning.
* Scanning results show up in the database, in MADmin, and in OSM-RM. Everything OK.

But an empty column.

![image](https://user-images.githubusercontent.com/4874269/63131525-4d1dc980-bfbe-11e9-9ed6-3baf8134dcb6.png)

**Environment:**
* `dev` branch, latest commit (https://github.com/Map-A-Droid/MAD/commit/0d97dc25f9680b75cf1821dc96ff17511319e37a)
* py3.7
* Raspbian Buster
* PogoDroid/RGC on an ATV

**Configuration that caused it:**
* MITM mon scanning
* 0.5km² geofenced area
* init mode, 10 init rounds

Nothing special. Basic setup according to the docs.

**Comment by nepixl** [comment]
Cannot confirm.
Theres a problem on your end.
![tasdf](https://user-images.githubusercontent.com/41138223/63144120-bec33b00-bff1-11e9-9e96-58b7224c535f.PNG)

**Comment by sn0opy** [comment]
This value won't get filled in init mode. It isn't handled properly anyway, since it only gets filled after a certain condition instead of a simple "received data? Fine, update".
