### ISSUE TITLE
Error message meant for no_ocr shown only when no_ocr is disabled.

### ISSUE THREAD

**Issue by sebastienvercammen** [Map-A-Droid/MAD#331]
The configuration option `no_ocr` will apparently be removed. To make this obvious, an error message was added.

Unfortunately, the message is only shown when `no_ocr` is **disabled** instead of enabled.

**Environment:**
* `dev` branch, latest commit (https://github.com/Map-A-Droid/MAD/commit/0d97dc25f9680b75cf1821dc96ff17511319e37a)
* py3.7
* Raspbian Buster

**To fix:**
Right here: https://github.com/Map-A-Droid/MAD/blob/dev/start.py#L240

https://github.com/Map-A-Droid/MAD/blob/0d97dc25f9680b75cf1821dc96ff17511319e37a/start.py#L240-L241

**Steps to reproduce:**
1. Run MAD **without** `no_ocr`.

**Comment by sn0opy** [comment]
Should've been a warning anyway. With the removal of all OCR scanning modes in a few weeks, this part will be removed as well.
