### ISSUE TITLE
Deleting an Area does not remove it from Walker.

### ISSUE THREAD

**Issue by sebastienvercammen** [Map-A-Droid/MAD#332]
Deleting an Area via the Area settings does not remove the previous assignments, causing Walkers' settings to show assigned Areas that no longer exist.

I'm not sure if this has additional consequences, I didn't let the non-existing Area's assignment stick around to figure that out. The mismatch in data shouldn't exist, otherwise it's just a matter of time till it breaks something.

Area in this screenshot was deleted but is still assigned:

![image](https://user-images.githubusercontent.com/4874269/63131921-b7833980-bfbf-11e9-9a82-1c5d095a9860.png)

**Environment:**
* `dev` branch, latest commit (https://github.com/Map-A-Droid/MAD/commit/0d97dc25f9680b75cf1821dc96ff17511319e37a)
* py3.7
* Raspbian Buster

**To fix:**
Automatically remove all assignments of Areas that are deleted.

**Steps to reproduce:**
1. Configure a working MAD setup with at least one Area assigned to a Walker.
2. In the Area settings tab, delete the assigned Area.
3. Open your Walker's settings (where you see the assigned areas).

Your Walker is still assigned to an Area that doesn't exist.

**Comment by sn0opy** [comment]
A rework of the mapping editor is already in progress. I'd say we close this for now, since the old editor is going away anyway
