### ISSUE TITLE
& Symbol is not 'percent-encoded', causing issues with pages

### ISSUE THREAD

**Issue by DexterKomio** [Map-A-Droid/MAD#333]
Using an & symbol is confirmed causing a error in the Walker section, when navigating to it results in an empty page. If a percent-encoded ampersand is manually typed in, you can access the page info as normal:

Name: This & That
URL: config?type=walker&area=walker&block=fields&edit=This_&_That
expected:config?type=walker&area=walker&block=fields&edit=This_%26_That
<img width="503" alt="Failed Ampersand" src="https://user-images.githubusercontent.com/7410274/63212128-e7206780-c0cd-11e9-9746-e2e790721a8f.png">

Additionally, it seems that it causes an issues when deleting the Walker

**Comment by Expl0dingBanana** [comment]
This should be resolved with #383 / #390

**Comment by Expl0dingBanana** [comment]
This issue can be resolved with #411 into master

**Comment by sn0opy** [comment]
Fixed, as #411 has been merged.
