### ISSUE TITLE
MADmin Walker settings bugged "Back to editor" link.

### ISSUE THREAD

**Issue by sebastienvercammen** [Map-A-Droid/MAD#338]
**Environment:**
* `dev` branch, this commit (https://github.com/Map-A-Droid/MAD/commit/0d97dc25f9680b75cf1821dc96ff17511319e37a)
* py3.7
* Raspbian Buster

**Steps to reproduce:**
1. Open MADmin's "Walker" settings tab.
2. On the Basedata of one of the walkers, click Edit.
3. In the Basedata, on one of the assigned areas, click Edit.
4. Top left corner of the screen, click "Back to editor".

**Problem:** This links to `http://host:port/showsettings?area=`, an empty area name, causing an empty editor screen.

![image](https://user-images.githubusercontent.com/4874269/63226557-6059b080-c1db-11e9-932c-ae9a34da9c42.png)

**To fix:**
Link back to the "Walker" settings.

Can be the generic `/showsettings?area=walker` for a quick fix, or the specific selected Walker's settings.

**Comment by sn0opy** [comment]
Going to close this one, since this is going to change with the madmin rework anyway
