### ISSUE TITLE
Hang on Premium Raid Pass cleanup

### ISSUE THREAD

**Issue by boby360** [Map-A-Droid/MAD#375]
When bag is full it attempts to delete the premium raid pass. When it does it it clicks it, attempts to get the maximum amount by clicking + and then 

[           MITMBase:97  ] [ WARNING] Timeout waiting for data
[       WorkerQuests:540 ] [   ERROR] Unknown error clearing out Premium Raid Pas
(YES this says Pas and not Pass in the logs)

![Screenshot_20190905-221545](https://user-images.githubusercontent.com/1607258/64402926-651bc280-d02b-11e9-9968-c8030c8d622e.png)

**Comment by JabLuszko** [comment]
If you really want to edit then it's here. https://github.com/Map-A-Droid/MAD/blob/dev/worker/WorkerQuests.py#L456

Stop buying premium raid passes on workers/doing researches. Use them or delete them once and forget about that "problem".

**Comment by boby360** [comment]
It should be very little effort to just add it to auto Cleanup. Which it has been. Except it wasn't done properly. It should either be removed from auto cleanup or made so it actually works. Not somewhere in the middle putting the account/phone in a endless loop.

**Comment by Grennith** [comment]
I guess we can close this since we have "Premium" and "Raid" excluded from deletion?
