### ISSUE TITLE
Toggle Magisk on/off causes 'device not supported' error and SafetyNet=false

### ISSUE THREAD

**Issue by kamieniarz** [Map-A-Droid/MAD#407]
I've noticed that after 2 months of working 24/h my 2 phones Nexus5 and GalaxyS5 started having issues with 'device not compatible' error. I'm pretty sure it started happening after I pulled commit https://github.com/Map-A-Droid/MAD/pull/399. I've noticed that everytime I have this error, POGO in Magisk Hide is not fully checked. 

After I fully check POGO in Magisk Hide, clear game data and reboot phone everything is fine. 

IF this feature rly helps some people, maybe don't enable it by default but give us an option to enable/disable it?

**Comment by boby360** [comment]
Iv noticed over the last few months that pogo is never fully checked anymore. This happened prior to the commit.

**Comment by kamieniarz** [comment]
That doesn't have to be the issue - I only mentioned what I've noticed. Maybe this feature is an issue by itself.

**Comment by chr2002qw** [comment]
In current master Magisk toggle ist fired AFTER a detected "not compatible" So it can´t be the issue for this. But I will revert back to magisk toggle after screentype.FAILURE. This helped me and is not in current master. I noticed more "not compatible" maybe because toggle is removed from screentype.FAILURE.

**Comment by kamieniarz** [comment]
You sure? As far as I remember it was ment to toggle hide after 2 login failuers, not after detecting 'device not compatible' error.

**Comment by chr2002qw** [comment]
Code has changed ;-) Look at /worker/WorkerBase.py lines 631 - 651.

**Comment by crhbetz** [comment]
As of https://github.com/Map-A-Droid/MAD/commit/9f7232f24a648abe1dc5ac630c86a54e16b744f7 it only toggles Magiskhide when the safetynet screen shows up: https://github.com/Map-A-Droid/MAD/blob/babd9f0c53cd83c135c7aa5412d2133e3e31c01c/worker/WorkerBase.py#L633

I have used this approach externally for months (firing the command through ADB) and it got rid of the safetynet screen very reliably.

I didn't even reboot, just `am force-stop com.nianticlabs.pokemongo` - maybe this reboot could be replaced with `self._restart_pogo()` ?
https://github.com/Map-A-Droid/MAD/blob/babd9f0c53cd83c135c7aa5412d2133e3e31c01c/worker/WorkerBase.py#L642

**Comment by kamieniarz** [comment]
I checked out to https://github.com/Map-A-Droid/MAD/commit/a8706c37357a2b7ec00752cb78bf3302e8c99492 and my issue is gone...

Is it just a coincidence that before `toggle magisk` commit everything was fine, after updating mad I had issue with 2 phones few times (not only once or twice) and after I switched back to commit from 26.09 everything is fine again?

**Comment by crhbetz** [comment]
I just can't see how the magisk toggle function could cause the 'device not compatible' error (`ScreenType.SN`), when the function is only used _after_ that screen shows up.

**Comment by kamieniarz** [comment]
I think this feature was an issue for me before ScreenType.SN detection was added. Looks like everything works now
