### ISSUE TITLE
import_allspawns.sh -> Config.ini not found

### ISSUE THREAD

**Issue by Massel84** [Map-A-Droid/MAD#41]
I wanted to extract the spawnpoints from my old rocketmap database (which I also use directly as the database connection in the config.ini and for running MAD).
So I edited file import_allspawns.sh with "database_old" (Which is same connection than in config.ini). The path to the config.ini is default ( configs/config.ini )

I tried to execute the import_allspawns.sh script in folder /scripts and got the error, that the config.ini could not be found. I also tried it with the complete path to config.ini in the script, and also with the a copy of config.ini in script folder. Nothing worked as excpected.
I am using Ubuntu server and the Scanner itself with MITM is running fine (with one Device).
I also tried to run from directory MAD directory as: sh scripts/import_allspawns.sh but I got the same error.

Error
import_allspawns.sh: 35: import_allspawns.sh: [[: not found
Unable to find your MAD config. You should be running this in the MAD directory

**Comment by crhbetz** [comment]
>I also tried to run from directory MAD directory as: sh scripts/import_allspawns.sh but I got the same error.

You're running the bash script in dash, not bash:
`ls -l /bin/sh
lrwxrwxrwx 1 root root 4 Jul 26  2016 /bin/sh -> dash`

Use `bash import_allspawns.sh` or make it executable and run it with `./import_allspawns.sh` from bash.

**Comment by Massel84** [comment]
omg. i'm new to linux, so for me executing a script was "sh script.sh". Do not know the difference between dash and bash. Sorry for that stupid request but thanks a lot for the help :)

**Comment by krzee** [comment]
to hopefully help clear it up a little since you say you're new:
the first line of the script says what shell it runs in. by typing sh before the script you told the script to ignore that and run in sh (which in your setup is actually dash).
