### ISSUE TITLE
Madmin throws 404s if using nginx subdirectorys instead of subdomains

### ISSUE THREAD

**Issue by chr2002qw** [Map-A-Droid/MAD#441]
New Madmin_rework contains "/" at the beginning of most url inside madmin code.

This breaks using madmin behind reverse proxy by using subdirectorys (eg. www.example.com/madmin) instead ob subdomains (eg madmin.example.com)

Not everyone can use subdomains depending on DNS Providers.
Current subdirectory users who CAN switch to subdomains need to reconfigure their ssl.

It would be better to remove the beginning "/" from all urls inside Madmin code.

**Comment by sn0opy** [comment]
There's no need to fix this within MAD. Either use rewrite rules or properly set your `proxy_pass` directive. Nginx will handle it properly with either of theses options.
