### ISSUE TITLE
madmin doesn't run nicely behind reverse proxy

### ISSUE THREAD

**Issue by DrMurx** [Map-A-Droid/MAD#442]
I currently use an nginx based entrypoint proxy to have SSL support for madmin, RGC and PogoDroid and map these services to 3 virtual locations within my vhost. However, madmin doesn't run nicely as service behind a reverse proxy. 

That's because Flask's (actually werkzeug's) URL handling doesn't support such as setup out of the box. Werkzeug includes the `ProxyFix` middleware to mitigate this problem, but it requires any URL to be created via `Flask.url_for()` which madmin - most of the time - does not.

For the time being, I've worked around this issue with a bunch of freaky rewrite and text substitute directives for an nginx reverse proxy setup, but this is very error prone.

I'd be willing to provide a PR to address the issue. It would generate any URL in madmin with `url_for` and add the `ProxyFix` middleware.

**Comment by sn0opy** [comment]
What's the actual problem? If you want to put your MAD into a subdirectory, you might've configured your nginx the wrong way. See https://github.com/Map-A-Droid/MAD/issues/441#issuecomment-544205121

**Comment by DrMurx** [comment]
The problem is that MAD returns HTML containing absolute URLs starting from root level. This can't be fixed on nginx level with `proxy_pass`/`rewrite` as you suggest, since those directives would modify the *request* to go to the correct (internal), not the generated *response* with href/src pointing to the wrong URLs. 

Also, behind a reverse proxy MAD would assume that it runs on http (because it doesn't know about the https used in front of the proxy), so whenever it issues a redirect it will do so to an http target. 

Using `url_for` to create URLs and then an additional middleware which injects the correct protocol and directory seems to be the common solution to this issue.

**Comment by chr2002qw** [comment]
The best solution would be removing the "/" from all urls. And follow the formerly url structure before rework. There all worked like a charm. I suggested, but i got a non working solution tip back and lost many hours useless work :-( Switched back to pre rework master.

**Comment by DrMurx** [comment]
@chr2002qw 

This is how I solved it for the time being, using nginx's `sub_filter`, but that filter doesn't allow regular expressions, so slight changes in the returned HTML might already break the substitution.

```
location ~ /mysubdir/(.*) {
    proxy_set_header Host $host;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Ssl https;
    proxy_set_header X-Forwarded-Proto https;
    proxy_set_header X-Forwarded-Port 443;
    proxy_http_version 1.1;
    proxy_pass http://madmin:5000/$1$is_args$args;

    sub_filter 'src="/' 'src="/mysubdir/';
    sub_filter "src='/" "src='/mysubdir/";
    sub_filter 'href="/' 'href="/mysubdir/';
    sub_filter "href='/" "href='/mysubdir/";
    sub_filter 'data-identifier="/' 'data-identifier="/mysubdir/';
    sub_filter "data-identifier='/" "data-identifier='/mysubdir/";

    sub_filter 'url: "/' 'url: "/mysubdir/';
    sub_filter 'url : "/' 'url : "/mysubdir/';
    sub_filter "url: '/" "url: '/mysubdir/";
    sub_filter "url : '/" "url : '/mysubdir/";
    sub_filter "window.location.replace('/" "window.location.replace('/mysubdir/";
    sub_filter ".attr('href', '/" ".attr('href', '/mysubdir/";
    sub_filter ".attr(\"href\", '/" ".attr('href', '/mysubdir/";

    sub_filter_once off;

    proxy_redirect ~http://[^/:]+(?::\d+)?(/.*) https://example.com/mysubdir$1;
}
```

**Comment by chr2002qw** [comment]
Since iam on production, i need a working and stable system. I found a similar solution. Its dangerous for production. Next git pull can break everything.

**Comment by sn0opy** [comment]
> Since iam on production, i need a working and stable system. I found a similar solution. Its dangerous for production. Next git pull can break everything.

wow wait. Master is working just fine and without any breaking issues. It's your custom setup causing the issue!

**Comment by DrMurx** [comment]
> It's your custom setup causing the issue!

I would counter that reverse proxies are very common, especially if you want SSL, or are limited in what you can wire to the domain root.

Flask provides `url_for` for a good reason. And once again I offer to provide a PR addressing this issue.

**Comment by chr2002qw** [comment]
> 
> 
> > Since iam on production, i need a working and stable system. I found a similar solution. Its dangerous for production. Next git pull can break everything.
> 
> wow wait. Master is working just fine and without any breaking issues. It's your custom setup causing the issue!

Mad istself workes fine. On pre rework and on rework. Whole scanning is working on both versions. Just accessing madmin via reverse proxy is broken.
Using madmin behind nginx subdirectorys is not as uncommon. Not everyone can use subdomains relaying on our dns providers and wildcard certificates.
Why not just removing the beginning "/"s from the urls and everything should work like pre_rework ? I can do it myself, but i dont know if i find all them in the code :-)

**Comment by DrMurx** [comment]
@chr2002qw Removing the leading `/` doesn't solve the issue, it would make the browser assume all URLs being *relative* to the current directory, so if you're at `https://example.com/madmin/settings/devices`, a relative link to `settings/areas` would make the browser go to `https://example.com/madmin/settings/settings/areas`.
