### ISSUE TITLE
version.json causing issues when running multiple instances out of one directory

### ISSUE THREAD

**Issue by crhbetz** [Map-A-Droid/MAD#443]
When running multiple, separate instances of MAD out of the same directory, utilizing the `--config` and `--mappings` options, the current approach of tracking major changes through a single entry in version.json is not suitable.

For every instance's first run after an update which increases the version, you have to manually set back the version number in version.json so all the instances can go through the update procedures.

I haven't had the time to look into solutions. As these version steps are usually related to changes in the database or config files, maybe it would be suitable to store the version number in database? That would make sure that database changes are run once per database.

**Comment by sn0opy** [comment]
Running multiple instances of MAD is officiall not supported. Even if it worked in the past, it was still not supported. These parameters are not meant to enble multi-instance support but rather a way to change the default path for specific config parameters.

Everyone, feel free to create a PR enabling proper support for this.

**Comment by sn0opy** [comment]
Also opened up an extra issue for further discussion of things that needed to be kept track of: #444
