### ISSUE TITLE
Add proper multi-instance support to MAD

### ISSUE THREAD

**Issue by sn0opy** [Map-A-Droid/MAD#444]
Due to heavy internal changes, running multiple instances broke. Eventhough this was not officially supported in the past, it just worked. This issue is meant to keep track of things that needed to change or being implemented to get actual multi-instance support into MAD

- migrations need to be issues for alternative databases or config files
- when running multiple instances, things like the trs_status page need to properly reflect devices within a specific instance

**Comment by crhbetz** [comment]
Just to clarify - I realized there's probably two types of "multi-instance" ...

1. using one database, targeting one area (purpose: distribute devices accross multiple instances probably for stability)
1. using two databases, two separate areas, two separate MADmins, etc (purpose: keep those areas strictly separated)

In #443 I was implying alternative 2, which will probably have a different set of unique issues (avoiding using the same files in `files/` comes to mind).

**Comment by sn0opy** [comment]
The trs_status part has been fixed via bfbadcd15c6a5b8da701e561178149c8ec5a28d6.

For the other part, storing the current migration version in the DB would be a good idea I guess.

**Comment by Expl0dingBanana** [comment]
Have all concerns around multi-instance single DB been addressed?
