### ISSUE TITLE
Possibility to split GitHub discord feed

### ISSUE THREAD

**Issue by dkmur** [Map-A-Droid/MAD#445]
Would it be possible to split the MAD github feed in “Issue’s/idea’s” and “commits to master/dev/projects”?

I like the concept of having the wishlist on github so all information on a subject is combined but due to this I find it harder to keep an eye/overview on MAD commits to master or projects. Two feeds would resolve that.

**Comment by sn0opy** [comment]
Not really something, that belongs here as an issue, but I just created a seperate channel showing ONLY push events. There's no way to make this work for seperate branches tho. In the end, you can no mute the `#mad-all-github` channel, if you only care about changes on the code.

**Comment by krzee** [comment]
"Not really something, that belongs here as an issue"

Just curious, where should it belong? I thought this is where you want wishlist items now?

**Comment by sn0opy** [comment]
> "Not really something, that belongs here as an issue"
> 
> Just curious, where should it belong? I thought this is where you want wishlist items now?

Well, ask on Discord and hope to get this sorted, or retry later. Using GH issues for every sort of request, question and so on will just clutter up things in the future.
