### ISSUE TITLE
Reinstate the "Postion in walker" button to madmin rework

### ISSUE THREAD

**Issue by Axiangel** [Map-A-Droid/MAD#454]
The button for entering the areas position in a walker was removed. However it was needed to quickly move the top area from the Paris walker to the bottom to prevent MAD from re-running those areas while still keeping them in the walker for the next account. 
An alternative would be to add a "append to list" button to move f.i. paris1 to after paris40. Perferrably abling the user to select multiple areas and append them to the end of the walker.

Currently a user is forced to drag the area to the end of the list, which is incredible time consuming on a cellphone when you need to repeat it a few times.

**Comment by DrMurx** [comment]
I would propose adding "Send to top" and "Send to bottom" buttons to each list item. Those two options will be the most likely use case.

**Comment by Axiangel** [comment]
That would work ideally in my case (as mentioned as an alternative). ^^ Doing this on a PC is rather quick with the use of home and end buttons, but on cellphone today it's hideos.

**Comment by Axiangel** [comment]
I'm not sure this is needed anymore after the latest updates on RGC. Perhaps other ppl find this useful, but my needs are filled with the RGC update. Feel free to close if you agree.
