### ISSUE TITLE
Enable POGO permissions from phone settings instead of using OCR

### ISSUE THREAD

**Issue by kamieniarz** [Map-A-Droid/MAD#459]
As title says - I think it would be more stable and more efficient to give permissions to POGO via app settings in phone settings after resetting game data. Detecting 'Allow' buttons in some phones doesn't work as good as in ATVs

**Comment by Grennith** [comment]
We could probably make use of `adb shell pm grant app.on.device android.permission.XXX`
Would that be suitable for use in https://github.com/Map-A-Droid/MAD/blob/master/mapadroid/ocr/screenPath.py#L338 and just grant all the permissions, restart the app and see if it works out? @cecpk

**Comment by kamieniarz** [comment]
It's done already I guess
