### ISSUE TITLE
Route generation freezing

### ISSUE THREAD

**Issue by 0xC1A551C** [Map-A-Droid/MAD#465]
If you clear all your routes (10+) and try to regenerate them every time mad will get stuck after it completes a route. This usually happens to me on the last few routes left. Restarting mad resumes regeneration until it completes.

Some other users have reported this. It happens to me every time.

I have 16GB ram dedicated to this server along with a intel pentium skylake dualcore. Could post logs if needed.

**Comment by sn0opy** [comment]
This is a known bug, but there's no fix for it yet. If you restarted MAD, it will just continue with the routes that haven't been generated yet.

**Comment by 0xC1A551C** [comment]
Just wanted to say this still happens on the latest version (noticed there was mention of a possible fix in a commit)

**Comment by Expl0dingBanana** [comment]
This occurs when the multiprocess.pool does not successfully trigger the threads (https://github.com/Map-A-Droid/MAD/blob/master/utils/s2Helper.py#L155).  It will not begin the recalculation and as @sn0opy mentioned, a restart of MAD is required.

**Comment by sn0opy** [comment]
Is this still a thing?
