### ISSUE TITLE
IV mitm shows Type RAIDS in Priority Routes

### ISSUE THREAD

**Issue by ChaosEmpire** [Map-A-Droid/MAD#470]
When activating show priotiry routes for IV mitm device it shows huge (raid view size) dots
also in list its shown as RAIDS, not iv mitm

**Comment by ChaosEmpire** [comment]
the iv mitm device is in excluded area of a mitm raid area, seems this has messed up the things

**Comment by sn0opy** [comment]
Guess that one needs an overhaul anyway since iv_mitm has no timings to display the location circle properly. Probably going to remove it completely, since it's useless.
