### ISSUE TITLE
Processing ScreenType.FAILURE doesn't work for PTC accounts

### ISSUE THREAD

**Issue by kamieniarz** [Map-A-Droid/MAD#485]
***I'm using 3 phones and 15 atv - 3 phones and 1 atv have PTC accounts and according to logs this issue affects only these devices. Devices with Google accounts are fine***

So it looks like Processing ScreenType.FAILURE simply doesn't work when worker is using PTC account. Device is rebooting after processing screen failure and so on so in fact it gets stuck in a loop.

I've noticed that this loop lasts until I manually press "TRY A DIFFERENT ACCOUNT" - after that MAD simply log back in PTC account. I have confirmed that solution multiple times on all 4 devices using PTC accounts.

So my request is to make MAD press "TRY A DIFFERENT ACCOUNT" when ScreenType.FAILURE appears. This solution could be available only if `logintype: ptc` but it also should work for Google accounts.

**Comment by kamieniarz** [comment]
I've never seen such a recommendation before so I've created PTC account at the beginning of my journey with MAD. I assume there might be users with PTC accounts also.

Anyway it's still an issue and if that requires like 10mins of work to fix I'd be grateful cause I don't like the idea to play with level mode for 4 accounts for the next 5 days :/

**Comment by sn0opy** [comment]
![image](https://user-images.githubusercontent.com/49074/67788504-c16ef180-fa72-11e9-8451-b9078dafce74.png)

![image](https://user-images.githubusercontent.com/49074/67788524-caf85980-fa72-11e9-9014-ea70f3a51159.png)

![image](https://user-images.githubusercontent.com/49074/67788537-d055a400-fa72-11e9-8195-6921c13499e3.png)

![image](https://user-images.githubusercontent.com/49074/67788562-dba8cf80-fa72-11e9-8bcc-b9db265b2d6b.png)

![image](https://user-images.githubusercontent.com/49074/67788581-e5cace00-fa72-11e9-9a50-74200a2ef52b.png)

That's literally the first page of search results on Discord.

**Comment by temp666** [comment]
PTC is work fine when you have clear game data and screendetection as true. If the problems come then MAD will log in again. It's Niantic...

**Comment by cecpk** [comment]
@kamieniarz 
pls test this branch
https://github.com/Map-A-Droid/MAD/tree/fix_issue_485

**Comment by sn0opy** [comment]
@kamieniarz any feedback?

**Comment by kamieniarz** [comment]
No, sorry. I used your advices and switched PTC accounts to google ones so there was no reason to test this branch

**Comment by ColdShadow80** [comment]
Wasnt this fixed already?
