### ISSUE TITLE
delay_after_prio_event value when cleared is not saved

### ISSUE THREAD

**Issue by madBeavis** [Map-A-Droid/MAD#495]
Mon-mitm mode.  Set a value for delay_after_prio_event, hit save.  Set the value to empty to clear it and save.  It retains the prior value.  To fix, one has to stop mad, edit mapping file by hand and restart mad.

**Comment by Expl0dingBanana** [comment]
I am working on a fix for this so the UI only sends elements that has changed and the API will always process the elements that have changed.

Until the fix is in place, you should be able to edit the file and click on 'APPLY SETTINGS' on the UI to pull in the changes.
