### ISSUE TITLE
Update scripts/SQL/rocketmap.sql

### ISSUE THREAD

**Issue by muckelba** [Map-A-Droid/MAD#505]
The current provided schema is outdated. 

@daangroot can you provide a clean OSM-RM schema? 

All the trs_* tables should be in version.py, right?

**Comment by sn0opy** [comment]
Also:  `trs_status` is completely missing either from the .sql file or from the version.py.

**Comment by sn0opy** [comment]
Not sure, where that bug actually lies, but we have several methods, that perform checks right on startup if several tables to exist. trs_status is one of them.

**Comment by muckelba** [comment]
Maybe it's a good idea to fully integrate the minimal MAD schema to the startup without tables. Including the normal RM tables

**Comment by Expl0dingBanana** [comment]
This has been implemented with the patcher rework.  If any of the RM devs could comment on the schema @ https://github.com/Map-A-Droid/MAD/blob/master/scripts/SQL/rocketmap.sql that would be great.

**Comment by Expl0dingBanana** [comment]
The base implementation for MAD and RM has been included in the rocketmap.sql file
