### ISSUE TITLE
Cofagrigus misspelled in en/pokemon.json

### ISSUE THREAD

**Issue by madBeavis** [Map-A-Droid/MAD#518]
Cofagrigus misspelled in en/pokemon.json

mon# 563

**Comment by boby360** [comment]
mon# 413 (wormadam) is also missing from en/pokemon.json

**Comment by sn0opy** [comment]
@boby360 would you like to fix that in your PR as well?

**Comment by boby360** [comment]
The issue is that wormadam uses cloaks and I don't think mad has support for that. So the Pokemon type can't be accurate. A simple option is to simply make it just bug type. But this won't be accurate and could conflict with other things. @sn0opy
