### ISSUE TITLE
Can't click on ball for menu and X to dismiss on HiRes device

### ISSUE THREAD

**Issue by cp06** [Map-A-Droid/MAD#520]
Have multiple Moto Z2 Force. 2560 x 1440
When quest scanning and the bag fills. i don't see any taps on pokeball, but see it try to tap "items button" in the menu. (which ultimately taps on the grass to the right and then screen slowly spins as it trys to scroll) 
It also seems to lag closing menus, I believe it using the back button. 
Taps on battle in rocket stops(maybe normal now, haven't watched questing bots in sometime)
I'm having 2 LG G5 delivered in a few days that are also 2560x1440, so i can test it on a different model with hi res.

**Comment by cp06** [comment]
![screenshot_MotoZF2](https://user-images.githubusercontent.com/20586960/68321132-c4776c80-0086-11ea-818f-f75d5f61fd8c.jpg)

**Comment by cp06** [comment]
![screenshot_MotoZF2](https://user-images.githubusercontent.com/20586960/68321861-0f45b400-0088-11ea-9504-bdf1ce37924e.jpg)
![screenshot_MotoZF2 (1)](https://user-images.githubusercontent.com/20586960/68321863-0fde4a80-0088-11ea-9f22-b98a368e44a5.jpg)

**Comment by JabLuszko** [comment]
Can't you just force them to 1080p to save bandwidth, GPU, CPU and make it work? :)

**Comment by cp06** [comment]
Doesn't matter to me 🤷‍♂ 
Is there an easy or preferred way to force a lower resolution?

**Comment by cp06** [comment]
As newer devices become cheaper, this is going to be more of an issue.

**Comment by cp06** [comment]
Opps. I don't know what i'm doing :)

**Comment by cp06** [comment]
This happens on my Moto Z2 force phones and my LG G5. I tried both setting resolution with adb shell and with an xposed module(app settings). It seems like pogo is doing some behind the scenes magic and reverting to full resolution. The app seems to launch at low res and then instantly goes to highest res.

**Comment by cp06** [comment]
These devices do "work" sometimes, i think i had an old version of tesseract on my old server. They still struggle to click on x

**Comment by cp06** [comment]
There is definitely and issue with stock rom. Phones still struggled in lineage but were usable, but this issue has seemed to gone away recently? 🤷‍♂
