### ISSUE TITLE
MAD flags 'unhandled exception'

### ISSUE THREAD

**Issue by Axiangel** [Map-A-Droid/MAD#523]
I've been having this issue for a few days. It crashes after a few hours.
I pull after each crash, hopeing the issues would have been reported and solved already but it still crashes.
 Last night i updated RGC and rebooted hoping that would fix it, but the log is only a few hours after that.
As you can see there is a "normal" part in the middle and then more exceptions. After that, there are no more normal logs, just exceptions until i log in and terminate it.

https://pasteyour.cf/igelugegil.sql

**Comment by Axiangel** [comment]
Deleting version.json as adviced and retrying.

**Comment by sn0opy** [comment]
> Deleting version.json as adviced and retrying.

Did it help?

**Comment by boby360** [comment]
i have seen the occasional EOF error although no crashing.

**Comment by Axiangel** [comment]
Deleting version.json seems to have resolved the issue.
