### ISSUE TITLE
request ability to input a full list of mon# into IV window

### ISSUE THREAD

**Issue by krzee** [Map-A-Droid/MAD#534]
would be handy since many often just use a list somebody else compiles

**Comment by Expl0dingBanana** [comment]
As a workaround until implemented, a POST to the API should suffice for bulk-importing a list.
`curl -v -X POST -H 'Content-Type: application/json' http://localhost:5000/api/monivlist -d '{"monlist": "sweet_mon_list", "mon_ids_iv": [1,2,3,4,5]}'`

**Comment by sn0opy** [comment]
Duplicate https://github.com/Map-A-Droid/MAD/issues/457
