### ISSUE TITLE
Selecting area on quests page when using MADmin behind reverse proxy results in "Not Found"

### ISSUE THREAD

**Issue by hzpz** [Map-A-Droid/MAD#536]
I am using MADmin behind a reverse proxy with a path. To make this work with the new version, I need to set `madmin_base_path` properly:
```
madmin_base_path: /madmin/
```
With that, everything seems to work except when I try to select an area on the quests page. MADmin tries to send me to `/madmin?fence=myfence` which results in a "Not Found" error. It must send me to `/madmin/quests?fence=myfence` instead.

**Comment by Expl0dingBanana** [comment]
Please review the docs @ https://mad-docs.readthedocs.io/en/latest/installation/1.getting-started/#deploying-behind-a-reverse-proxy
