### ISSUE TITLE
Regression: webhook_excluded_areas does not work anymore

### ISSUE THREAD

**Issue by hzpz** [Map-A-Droid/MAD#541]
Before the rework I used to be able to exclude certain areas from being send to webhooks by specifying the area names as `webhook_excluded_areas`. That does not work anymore. 

It seems, that the internal name the MappingManager uses for areas changed to be the entry number in mappings.json instead of the actual name of the area. Therefore `MappingManager.get_all_routemanager_names` will return something like `['3', '2', '0', '1', '5', '4']` which breaks `WebhookWorker.__build_geofence_helpers`.

**Comment by sn0opy** [comment]
Fixed via https://github.com/Map-A-Droid/MAD/commit/2e9bd56432557301461ab851fa49d9d1f533e15f
