### ISSUE TITLE
Make MAD non-blocking for other areas on startup, if one of them needs route calculation

### ISSUE THREAD

**Issue by sn0opy** [Map-A-Droid/MAD#566]
Just to make sure we don't forget this in the future.

When MAD is restarted with at least one area calculating a new route, the whole starting process is delayed until calculation has finished.

**Comment by DrMurx** [comment]
I’ve a proposal on that one which I’d like to implement as soon as #539 is in master. 

In a nutshell, the route calculation would use an iterative approach, starting with a quick but not very optimal route and refining it continuously  until a satisfactory area size to path length ratio has been reached, or whatever other criterion should be used. This could even happen in background in a low prio thread without stealing precious CPU cycles from other processing.

Doing so will reduce delay if the route is needed immediately after startup or area creation, at the price of the first round being a little less effective.

**Comment by Expl0dingBanana** [comment]
A basic version of this is implemented into master.  As soon as the route is re-calculated (if optimized is required) it will disconnect / reconnect and use the new route.  If you wish to modify it to complete the route a new PR will need to be created.
