### ISSUE TITLE
reboot="" blocks shared settings

### ISSUE THREAD

**Issue by ChaosEmpire** [Map-A-Droid/MAD#570]
Creating a new device adds the line 
reboot="" 
to mappings.json

This entry blocks the reboot = true / false setting defined in shared settings

**Comment by ChaosEmpire** [comment]
I assume cool_down_sleep="" will cause same issue

**Comment by Expl0dingBanana** [comment]
This is fixed in PR-359, f048a2a

**Comment by crhbetz** [comment]
> 
> 
> This is fixed in PR-359, [f048a2a](https://github.com/Map-A-Droid/MAD/commit/f048a2aada411a5af3b530e50e71c8dd0f9d9c1a)

When/how will this show up in master? (sorry for my low git-fu)
I've been looking at some of those descriptions too.

**Comment by sn0opy** [comment]
> > This is fixed in PR-359, [f048a2a](https://github.com/Map-A-Droid/MAD/commit/f048a2aada411a5af3b530e50e71c8dd0f9d9c1a)
> 
> When/how will this show up in master? (sorry for my low git-fu)
> I've been looking at some of those descriptions too.

Test the PR. Report possible issues and speed up the merge process. There's no ETA

**Comment by crhbetz** [comment]
Yeah, I couldn't find the related PR because it's in https://github.com/Map-A-Droid/MAD/pull/539, not 359 (typo), and github wouldn't give me that info when clicking the commit. 🤷‍♂️
