### ISSUE TITLE
Devicestatus shows wrong "Last Data" times if browser is in a different timezone

### ISSUE THREAD

**Issue by DrMurx** [Map-A-Droid/MAD#571]
`moment.js` uses the browser's current time to create readable time offsets. However, if the browser is in a different timezone than the server, this results in wrong offsets which may cause irritations.

[Moment Timezone](https://momentjs.com/timezone/docs/) provides proper timezone support, leveraging new browser APIs to correctly detect the timezone, and has a sophisticated `guess` method if there's no such API.

**Comment by Expl0dingBanana** [comment]
Anything time-related in the trs_status table has been switched to timestamp.
