### ISSUE TITLE
Clear quests in madmin

### ISSUE THREAD

**Issue by clburlison** [Map-A-Droid/MAD#574]
Niantic likes events that start/end at 1pm PST. It would be great to be able to truncate the `trs_quest` database table from madmin.

**Comment by Expl0dingBanana** [comment]
Would this be better as a 'clear all quests in this area', or just 'clear every quest in the db'?

**Comment by sn0opy** [comment]
Things to consider: MAD does not actually remove quests. It just overwrites them after day change. If there's an option to remove quests, the quest statistic will be gone as well, since it completely relies on that.

**Comment by clburlison** [comment]
> clear all quests in this area
If the implementation is clicking on 8-10 different areas to do the clearing I dislike this option.

I think losing quest stats is worth it to make it easy to rescan quests mid-day. The problem is when rescanning quests twice due to these events our stats are already messed up. No way to keep track that we scanned pokestop XX twice on Dec. 12th. Truncate still seems like the right option, maybe just add text to state that quest stats will be lost?

**Comment by clburlison** [comment]
Resolved with mad plugins. closing...
