### ISSUE TITLE
Disable Encounters while quest scanning.

### ISSUE THREAD

**Issue by boby360** [Map-A-Droid/MAD#575]
Title says it all. Quest scanners on default encounter everything. This doesn't seem to be an option. In an environment where pokemon scanning is stopped after a certain time and quest scans start after that. encounters will continue to be sent via webhooks causing undesired late night pings. There are other methods to fix this however every other scanning type has the option so you would think so should this.

**Comment by DrMurx** [comment]
I don’t think that can be changed easily as the spawns come with the GMO and are written to the database as-is. They’re picked up from the database independently by the webhook worker. 

I also don’t understand the actual problem. I’d like to see rare spawns at any time even if the workers are in quest mode. If you want silence at certain times, you might be better with a filter in your notification tool.

**Comment by boby360** [comment]
just as it exists in mon-mitm. we don't have to encounter the pokemon that are seen. encounters also might slow down questing speeds due to the brief lag that is introduced while encountering.

**Comment by DrMurx** [comment]
Which option in the mon-mitm settings are you referring to?

**Comment by boby360** [comment]
mon_ids_iv

**Comment by DrMurx** [comment]
If I understood that correctly, mon_ids_iv gives only a priority to decide which 2 Pokémon are selected as encounters per location. If it’s undefined pogodroid will still create 2 encounters. 

There are no encounters done in quest mode to my knowledge. It just receives the spawns as it is with any more.

**Comment by boby360** [comment]
This has been brought to discord chat. Hart telling me that it doesn't on default encounter and any kind of encounters would be due to mis clicks on the screen while quest scanning. mon_ids_iv is used for the automated encountering. manual clicks are handled separately thus the issue.
