### ISSUE TITLE
Change google images to HTTPS or handle better.

### ISSUE THREAD

**Issue by boby360** [Map-A-Droid/MAD#576]
If using Quests within Madmin or quest_pub over HTTPS it will show that it isn't fully encrypted because there are images from an unencrypted source. Google supports both http and https for the images hosted. 

We could force https to be used for every image all the time.
Or we could have a variable in the config to change how its handled. with either a sql query built in to change pre existing images in the DB or a external script. Would most likely be a one time run script.

**Comment by Expl0dingBanana** [comment]
This feature has been implemented with the DB migration

**Comment by boby360** [comment]
Woohoo!! Thankyou.
