### ISSUE TITLE
Existing PrioQ gets dropped on every recalculation (mon_mitm)

### ISSUE THREAD

**Issue by crhbetz** [Map-A-Droid/MAD#579]
Bringing this over from discord for better readability and to keep organized.
I only looked at **mon_mitm** for this so far.
I'm not creating a PR because I'm not convinced I understand everything going on here and want to post it for discussion.

In `_update_priority_queue_loop`, `_merge_priority_queue` is used (L320), which returns a new (clustered) prioQ that doesn't take the existing prioQ in `self._prio_queue` into account, instead just replacing it.

https://github.com/Map-A-Droid/MAD/blob/20b8b0eb6477fb106d0b5422cc7640e17b8491b6/route/RouteManagerBase.py#L313-L327

https://github.com/Map-A-Droid/MAD/blob/20b8b0eb6477fb106d0b5422cc7640e17b8491b6/route/RouteManagerBase.py#L329-L338

`_update_priority_queue_loop` runs every 180 seconds in mon_mitm mode:

https://github.com/Map-A-Droid/MAD/blob/20b8b0eb6477fb106d0b5422cc7640e17b8491b6/route/RouteManagerMon.py#L6-L7

New Q items for mon_mitm are fetched through `retrieve_next_spawns` in dbwrapper.py.
I don't understand the database query there, but the function excludes spawns in the past, even explicitly stating so in the comment:
https://github.com/Map-A-Droid/MAD/blob/20b8b0eb6477fb106d0b5422cc7640e17b8491b6/db/DbWrapper.py#L797-L800

This results in the prioQ never containing spawns that are older than ~4 minutes. I think this is both unexpected behaviour and probably not intended, because the `remove_from_queue_backlog` would only do anything if set below ~3-4 minutes, which is way too aggressive.

The behaviour of discarding the previous prioQ was introduced in https://github.com/Map-A-Droid/MAD/commit/328e807fae87bcda212250fc4f5903c388e53b9f - apparently to fix issues of the prioQ getting too large.
I'd guess this problem would also be solved by setting either a reasonable default value for `remove_from_queue_backlog` (not 0) or a reasonable fallback value here:
https://github.com/Map-A-Droid/MAD/blob/328e807fae87bcda212250fc4f5903c388e53b9f/route/RouteManagerBase.py#L326-L327

I propose the following diff to try out and analyze reverting the change from April:
```diff
diff --git a/route/RouteManagerBase.py b/route/RouteManagerBase.py
index 94762b3..34cff2f 100644
--- a/route/RouteManagerBase.py
+++ b/route/RouteManagerBase.py
@@ -324,7 +324,11 @@ class RouteManagerBase(ABC):
     def _merge_priority_queue(self, new_queue):
         if new_queue is not None:
             with self._manager_mutex:
-                merged = list(new_queue)
+                logger.info("Merging existing Q of {} events with {} new events",
+                        len(self._prio_queue), len(new_queue))
+                merged = set(new_queue + self._prio_queue)
+                merged = list(merged)
+#                merged = list(new_queue)
                 logger.info("New raw priority queue with {} entries", len(merged))
                 merged = self._filter_priority_queue_internal(merged)
                 heapq.heapify(merged)
@@ -458,7 +462,11 @@ class RouteManagerBase(ABC):
             delete_before = time.time() - delete_seconds_passed
         else:
             delete_before = 0
+        lenbefore = len(latest)
         latest = [to_keep for to_keep in latest if not to_keep[0] < delete_before]
+        lenafter = len(latest)
+        if lenafter < lenbefore:
+            logger.info("Dropped from {} to {} because of remove_from_queue_backlog", lenbefore, lenafter)
         # TODO: sort latest by modified flag of event
         # merged = self._merge_queue(latest, self._max_radius, 2, timedelta_seconds)
         merged = self.clustering_helper.get_clustered(latest)
@@ -530,6 +538,7 @@ class RouteManagerBase(ABC):
                                                                   or self.starve_route)
                                                                  and self._prio_queue and len(self._prio_queue) > 0
                                                                  and self._prio_queue[0][0] < time.time())):
+                logger.info("The upcoming event is due at {}", datetime.fromtimestamp(self._prio_queue[0][0]).strftime('%Y-%m-%d %H:%M:%S'))
                 logger.debug("{}: Priority event", self.name)
                 next_coord = heapq.heappop(self._prio_queue)[1]
                 if self._other_worker_closer_to_prioq(next_coord, origin):
```

**Comment by Grennith** [comment]
Nice find! Cannot test atm, code looks good tho. Thanks!
Anyone else able to check if this is the case? @sn0opy ? :>

**Comment by Grennith** [comment]
Alright, I've put your suggestions on a branch, see commit c0bb3780fb94a318925d9fd603e02d6594dbc0e0.
However, I adjusted the loglevel of the drop-info to warning, since that basically implies that either the workers are not keeping up or something else is going wrong. #

**Comment by crhbetz** [comment]
Awesome! The loglevel makes sense. I hadn't thought about those log lines to be permanently added. Just quickly inserted them while diagnosing.

**Comment by crhbetz** [comment]
The proposed fix introduces other issues, for example it might re-introduce prio events into the queue as single events that had previously been clustered with another event.

Also, I think there's possible situations where it might cluster a new event with an old, already-clustered event, and thereby might push one of the previously clustered events out of detection range because it's location can't be taken into consideration upon the new clustering attempt.

I'll continue working on this and hopefully come up with a PR soon-ish to properly take on both this and https://github.com/Map-A-Droid/MAD/issues/596 (also by me).
