### ISSUE TITLE
Add easy "Pause/Unpause" for device scanning that doesnt affect other devices/workers

### ISSUE THREAD

**Issue by Silverlink34** [Map-A-Droid/MAD#589]
There are many occasions where it is necessary to quickly perform some action on a device manually. With MAD actively controlling it, this is near impossible.

Current solutions are:

- Stop MAD python instance/Run Config Mode
Issues with this solution: progress is lost for all workers, everything restarts
Benefits of this solution: with configmode running, all workers just sit at their last location or default location awaiting commands and pogo is still running. this is the perfect time to quickly change or do anything in PoGo on our devices.

- Use Idle mode facilities (area/walker settings)
Issues with this solution: progress is lost due to mappings reload. device closes out of pogo/turns off screen. We prefer to have Pogo open already. Need to re-open pogo, do what needs done, then set walker/area back to regular mode. 
Benefits of this solution: if you want to do something on your OWN device and log into the desired account that the device was on, then this is the best solution since pogo is closed out.

- Stop RGC on device directly
Issues with this solution: you better have a way to start it back up. also since RGC is stopped you no longer have device control and lose all madmin control. need a separate setup to manage device outside of RGC control. Lastly, the device/worker's own progress may be lost.
Benefits of this solution: other workers are not affected and continue working!! with an external setup with Tasker/FRep or other remote management software we can then automate other things while RGC isnt taking over. 

-Use "set location" madmin api and set a device's location for a long duration.
Issues with this solution: you need to make sure you set a good time or else when the time is up your walker/device will continue on with its route.
Benefits of this solution: Progress is not lost with anything, RGC control is maintained yet "paused" while POGO is still open and easily workable. If an easy "pause/unpause" feature were to be implemented, I think that deriving how the "set location" api is handling things it could be (hopefully) be easily modified to loop with a boolean instead of looping with a set seconds time limit being reached.

Suggestion for desired implementation:
Perhaps on Device Control page there could be an extra button to "Pause/Resume" under each device that would act as a toggle switch to stop RGC from interacting with the screen until resumed. On resume, progress should still be maintained.

IF you are low on man power, I would greatly appreciate being involved in this request if you would like to show me exactly where the "set location" api is actually located. To be specific, I am referring to the api of this http url: 
http://madmin.com/send_gps?origin=ATV1&coords=1.0,2.0&adb=False&sleeptime=600

**Comment by sn0opy** [comment]
If you want to perform things on device, just disconnect it from RGC. If you need to do it remotely, do it with a job via MADmin.

Not sure what else you want to do that needs your device to stand completely still. We're planning to modify MAD in a way to prevent it from reloading the configuration for everything it only one device or area is affected. 

This change requires so many things to be changed. That's not worth the time tbh

**Comment by Silverlink34** [comment]
Thank you kindly for your response. You may close this out.

**Comment by Expl0dingBanana** [comment]
Let's leave this open. It's something I would like to implement

**Comment by Expl0dingBanana** [comment]
This issue can be closed as the PR was merged.
