### ISSUE TITLE
Status Page issue while loading

### ISSUE THREAD

**Issue by ChaosEmpire** [Map-A-Droid/MAD#604]
[MainProcess|Thread-604] [PooledQueryExecutor:101 ] [   ERROR] Failed executing query: SELECT trs.origin, trs.currentPos, trs.lastPos, trs.
FROM trs_status trs
INNER JOIN madmin_instance mi ON mi.name = trs.instance
INNER JOIN settings_device sd ON sd.name = trs.origin AND sd.instance_id = mi.instance_id
WHERE trs.instance = %s, error: 1267 (HY000): Illegal mix of collations (utf8mb4_unicode_ci,IMPLICIT) and (utf8mb4_general_ci,IMPLICIT) for operation '='
----------------

fixed by changing 
collations of trs.instance from general to unicode

assuming trs.instance got implemented with instance feature, this could mean all will have wrong collation

maybe someone can check this in code

**Comment by DrMurx** [comment]
Do you use any non-ascii character as instance name?

**Comment by ChaosEmpire** [comment]
i never used instance
i have had double entries of empty and mad , removed the empty ones after i saw them in table
error happend with only mad instance names
but content of this row does not change the collation of the table row

**Comment by ChaosEmpire** [comment]
Wrong collation in DbSchemaUpdater
Line 190
           "ctype": "VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL FIRST",

**Comment by DrMurx** [comment]
I don’t doubt that this should be changed so that we use the same collation for all varchars in the database. However, the point is that the collation shouldn’t clash if there is no reason for it, so unless you have a character on the instance name specific to utf8mb4_unicode_ci which makes MySQL picking that one over utf8mb4_general_ci, there’s no obvious reason for this error to appear, and therefore I’m curiously why that’s the case in your setup.

**Comment by sn0opy** [comment]
Already fixed here and will be merged soon. https://github.com/Map-A-Droid/MAD/pull/600

**Comment by DrMurx** [comment]
By the way, Rocketmaps automagically changes the collation on all varchar fields of all tables during its startup sequence. I assume that’s why this went through unnoticed.

**Comment by ChaosEmpire** [comment]
as said, i neve rused instance, its even default in config

so after update my empty instance fields got filled with mad
so i have had some devices doubled, i removed those lines woithout mad inside
i never entered aninstance name anywhere

and mad should be ok for any collation...so i dont see an issue in my setup, anyway, i fixed it by changing the row

and in code is the wrong collation

i cant do more
