### ISSUE TITLE
MAD doesn't recalc the whole route if quests are missing on the current route

### ISSUE THREAD

**Issue by muckelba** [Map-A-Droid/MAD#612]
I'm not sure yet if that's just my issue or a general one, but hitting recalc in MADmin only calculated a route of stops that doesnt have quests today

**Comment by hrueppert** [comment]
My Routecalcs are also gone. It seems that the recalc of the missing stops inserted as new routecalc in the DB for the area.

So from 100+ stops only 3-4 (the missing one) stays as routecalc.

Only workaround for my, insert the backup after hit the recalc button for all areas oder recalc all areas.

**Comment by Expl0dingBanana** [comment]
Are you still experiencing this issue on latest master?

**Comment by muckelba** [comment]
I somehow do, yes. I just tested it in a area with 100% quests scanned today and MAD generated a route with only 4 stops in it. I tried that a few times and its always the 4 same stops.

**Comment by hrueppert** [comment]
My RC entries in the DB stays, no new routes in the DB without manually click recalc in madmin.

For controlling purposes i added a timestamp field to the table which is automatically filled or updated. The field shows all entries stable since 2019-12-13.

**Comment by muckelba** [comment]
Okay, seems like i'm just too stupid lol. I was on a wrong branch. Working now for me.

what about @hrueppert ?

**Comment by hrueppert** [comment]
Everything is stable since 2019-12-13, see posting above :-)
