### ISSUE TITLE
Make route filed editable/deleteable

### ISSUE THREAD

**Issue by ChaosEmpire** [Map-A-Droid/MAD#618]
Before the Database migration it was easy to delete a route calc file, as you knew the name, now you need to find the corresponding id from 3 tables, and at the end you dont know if somethign will break mad when you do it directly in sql cause of dependencies

also important, there is no easy way to edit the calec route, like we have been doing before database migration

The way geofences can be opened in madmin and edited would be perfect for routefiles
that way we would have an user friendly way of deleting routes..which else stay in database forever, and we can copy paste in route, to change starting area or optimize in other ways the route

**Comment by Expl0dingBanana** [comment]
Would getting the route calc by performing GET to /api/area/routecalc to get the list and POST to /api/area/routecalc be sufficient?

**Comment by ChaosEmpire** [comment]
From my point of view, its not sufficent

A very easy way to remove old routes
and or edit route entries is missing in the GUI

it would be the sufficient replacement for txt editing before db migration

API calls are for advantage users, or automatisation from my point of view
A regular user should be able to do basic tasks via the gui

geofence website is a very good example how i would expect a route webpage
