### ISSUE TITLE
only route calculationg (start parameter only_routes)

### ISSUE THREAD

**Issue by temp666** [Map-A-Droid/MAD#622]
since the big api update the start parameter `-or` doesn't seem to work anymore to calculate the routes.
I use a different system to calculate the routes to make it faster, but this is no longer possible with `sudo python3 start.py -or`

**Comment by Expl0dingBanana** [comment]
Is this still needed with being able to recalculate routes ad-hoc within MADmin?  Its non-blocking and does not disrupt the current route until completed.  Once completed it will force a reconnection of all devices in the area.

**Comment by muckelba** [comment]
That feature is used by ppl that are running their calcs on different machines. But since you have to copy your MAD setup anyways to do a calc, it does not really matter tbh

**Comment by temp666** [comment]
for me it was a help, because MAD runs on a rpi (i know it's not recommended) and some routes take hours for him to calculate them and i always did that on my laptop `-or` who calculated it faster.
But it looks like it's going to be handled differently now?

**Comment by chr2002qw** [comment]
Its not really needed anymore, but would recommend to keep it for current workflow of ppl still using it.

**Comment by Expl0dingBanana** [comment]
Can you test PR-657 and make sure its resolves the issue?

**Comment by temp666** [comment]
thanks, how can i test this?
Setting the value of recalc_status to 1 in the database did not help.

**Comment by Expl0dingBanana** [comment]
Switch to the PR:  `git fetch origin pull/657/head:tmp_pr && git checkout tmp_pr`.  Run MAD normally and test the `-or` flag
Switch back to master `git checkout master`
