### ISSUE TITLE
Add "Clear levelup data" to Devices Bulk Update drop down menu.

### ISSUE THREAD

**Issue by Silverlink34** [Map-A-Droid/MAD#628]
I feel like this would make switching user accounts a little easier. We wouldn't need to clear multiple devices one by one with this capability.

**Comment by ChaosEmpire** [comment]
wouldt it be better, to change the level system to save account info instead device info...so clearing wont be needed at all

**Comment by Silverlink34** [comment]
That actually is a really nice idea @Chaos

**Comment by Expl0dingBanana** [comment]
If you would like the stats to be per account versus per device please submit another feature request.  Closing this FR as it has been implemented to master.
