### ISSUE TITLE
Feature Request: Whitelist quests from deleting

### ISSUE THREAD

**Issue by Silverlink34** [Map-A-Droid/MAD#635]
In pokestop mode, level mode or not - mad will check quests and remove all quests. Deducing from the logs, it seems to be specifically looking for trash cans. I imagine that PogoDroid is actually intercepting the quest data directly, if any, and the quests are not actually determined and stored via viewing the research menu. So viewing the research menu is a task that is used specifically to clean quests. I assume that PogoDroid cannot intercept the quests at pokestops  if your quests are full. However, since screenshot technology must be being used to determine trash cans for amount of quests, would it be too hard of a stretch to make it check first from a list of specified quests that you would desire to not be deleted? Especially ones like "Spin # pokestops"?? You would of course be only able to 'whitelist' up to 2 quests, as the third one would be required for actually scanning quests every stop.

**Comment by ColdShadow80** [comment]
Why? OMG? Why?
We have enough accidental quests completed already.
Please don't.

**Comment by muckelba** [comment]
Maybe my English is too bad but I don't really see a benefit of not deleting quests

**Comment by Grennith** [comment]
I honestly don't see the benefit either

**Comment by Silverlink34** [comment]
Why would you not want to complete quests? Especially if you are in level mode? What if you had a walker and wanted them to have a daily research task completed? Please explain, I mean no offense.

**Comment by ColdShadow80** [comment]
Questing is not perfect. If you complete a quest it will not be deleted or clicked, it will just be there waiting for you to click.
If by any chance the reward is a Mon, and if by accident the not clicks on it, most likely will be stuck there until reboot.

Odds are height that the feature would break questing, unless you manually click on them.

Besides, why would I want any item other than lures or lucky eggs on a bot? It is not like I can use a rare candy or a silver pinneaple to help another account.

**Comment by JabLuszko** [comment]
> Why would you not want to complete quests? Especially if you are in level mode?

Because level mode in big city takes like 4 days. Stacking 4 quests for 4 day streak makes like 0.002% of needed XP progress on leveling up. Waste of everything - device time, resources, dev times to implement this.

**Comment by krzee** [comment]
MAD is not for botting.
This request should not happen.

**Comment by Silverlink34** [comment]
I will close this issue. You have made me aware of the additional bugs that would need overcame, and it is not as simple as I originally had thought. Thank you for your valued input.
