### ISSUE TITLE
MAD jobs are always "pending"

### ISSUE THREAD

**Issue by ColdShadow80** [Map-A-Droid/MAD#636]
MAD jobs are not starting.
 They seem to be "pending"  forever.
Are successfully added to queue but do not start.
Tested by jobs button in device menu and by trying to run MAD ROM update jobs by jobs menu selecting 6 out of a total 8 devices.

**Comment by boby360** [comment]
while this should be fixed. In my experience a page refresh shows the current/proper status.

**Comment by ColdShadow80** [comment]
> While this should get fixed. In my experience a page refresh shows the current/proper status.

Used to. Now they really seem not to start.

**Comment by cecpk** [comment]
Log ? please -v

**Comment by ColdShadow80** [comment]
Sent by PM

**Comment by ColdShadow80** [comment]
Fixed in commit 78b8090
FIX: Job queue with autojobs

Autojobs made normal jobs hang
