### ISSUE TITLE
Add surrounding L15 S2 cells for raid routes on MADmin map

### ISSUE THREAD

**Issue by sn0opy** [Map-A-Droid/MAD#641]
Since https://github.com/Map-A-Droid/MAD/pull/315 MAD uses actual S2 cells to calculate routes. Problem with that is, that the map does not reflect it. Gyms that seem to be outside of route circles are still being scanned due to the way the game receives the data.

We should probably add extra L15 cells to each route circle.

**Comment by Expl0dingBanana** [comment]
Raids was implemented with #665 but not implemented for the rest.  However I believe this now falls under #681
