### ISSUE TITLE
Prevent devices from rebooting

### ISSUE THREAD

**Issue by kamieniarz** [Map-A-Droid/MAD#664]
So basically when reboot device is false, devices can still reboot (eg when they can't inject in time). It would be nice if there would be an option to completly prevent mad from rebooting devices.

**Comment by LucianoNeo** [comment]
Still waiting for the fix...

**Comment by Expl0dingBanana** [comment]
Please test PR 871

**Comment by Expl0dingBanana** [comment]
@kamieniarz @LucianoNeo can either of you validate PR 871?

**Comment by kamieniarz** [comment]
I reported this issue 4,5 months ago so unfortunately no, I already gaved up on some settings

**Comment by LucianoNeo** [comment]
Same here, just discarded the phones that can't reboot...

**Comment by crhbetz** [comment]
I can confirm #871 working. Had multiple devices loop up to 100+ counts of  `not injected yet` with `reboot` set to `False` and `injection_thresh_reboot` at default/empty:

`[           mini01] [           MITMBase:261 ] [    INFO] PogoDroid on worker mini01 didn't connect yet. Probably not injected? (Count: 103/Unlimited)`
