### ISSUE TITLE
MADmin: render s2 cells in the frontend on the client

### ISSUE THREAD

**Issue by sn0opy** [Map-A-Droid/MAD#681]
Due to the addition of s2 cells for raid routes, the browser will load quite a lot of data every few seconds. This can hit server performence and bandwith at the same time.

Neither render polygons nor s2cell IDs on the server. The client only requires the route locations to calculate the rest on the client. There are javascript libraries to that can be used to render them.

Related: cell updates. They're also rendered on the server and sent to the client every few seconds once activated and changed/updated.

**Comment by Expl0dingBanana** [comment]
fixed with a399f10 and 23c65b5
