### ISSUE TITLE
Problems with MAD ever since 0c0f774 prioQ fixes for mon_mitm

### ISSUE THREAD

**Issue by PurseChicken** [Map-A-Droid/MAD#692]
An initial issue was created at:

https://github.com/Map-A-Droid/MAD/issues/673

This problem is back with the latest cda6216 commit. There have been multiple people experiencing this again and it appears to be related to having larger routes.

That said, not only do I suffer from that issue, really any build from 0c0f774 and beyond are causing issues for me. Either the issue noted above, where the devices are injected and PD is showing data being sent however MADmin shows no data for those devices. Or in the case where that issue was fixed in fix #677, then what starts happening is that PD says its injected but it doesn't appear to ever start sending data. The only way i have found to "kick it into gear" or to get it working is to push PogoDroid APK to the device again and it magically starts working again for awhile.

The only way i can go back to being stable again is to run "git reset --hard fac3719". Magically, almost instantaneously, all of my problems go away.

**Comment by sn0opy** [comment]
Please reuse the initial issue instead.
