### ISSUE TITLE
Add option to run configmode via start.py

### ISSUE THREAD

**Issue by muckelba** [Map-A-Droid/MAD#697]
Right now there's basically no way to run configmode with Docker since the image runs start.py hardcoded. Everything else like debug levels are configurable via config.ini, except for running configmode. I'm not sure about the technical background but setting a flag in the config telling start.py to start configmode.py should be enough.

**Comment by Expl0dingBanana** [comment]
This has been implemented in the branch 'start_refactoring' by adding a new startup argument, -cm or --config_mode.  Please test when you get a chance.

**Comment by Expl0dingBanana** [comment]
This has been implemented in PR #840 but requires further testing

**Comment by Expl0dingBanana** [comment]
This has been merged into master.  Closing this issue.
