### ISSUE TITLE
last_updated column in database table settings_routecalc does not update

### ISSUE THREAD

**Issue by Seandals** [Map-A-Droid/MAD#706]
This database column does not seem to be updating ever.

**Comment by Expl0dingBanana** [comment]
@Seandals Can you please validate the fix with #710 ?

**Comment by Seandals** [comment]
@Expl0dingBanana Yes, thank you. This is working perfectly with #710 applied.

**Comment by Expl0dingBanana** [comment]
Did you see this after updating PD?
