### ISSUE TITLE
Restart Counter does not raise.

### ISSUE THREAD

**Issue by chr2002qw** [Map-A-Droid/MAD#708]
Restart Counter on Madmin Status Page does not raise on "Timeout waiting for Data" in log.
But the device got restartet after "Too many timeouts" in log.

This seems to be just a Bug on the Status Page.

Mad is on current master:c9225a8d052566b24a363669a01b515254a4abec

**Comment by Expl0dingBanana** [comment]
@chr2002qw Please test PR-728 and validate the fix

**Comment by Expl0dingBanana** [comment]
This has been merged to master.  Please re-open if you experience this issue.
