### ISSUE TITLE
Using MADmin APKs smart updates fails on large files.

### ISSUE THREAD

**Issue by BadWolf0081** [Map-A-Droid/MAD#709]
Whenever attempting to use the smart update for pogodroid or for pogo itself I regularly get "Last Status: Failure" and the job is stuck in "Starting"  screenshot and log provided. Updating RGC seems to work just fine, and occasionally one of these might sneak through and work if i keep hammering it.  If you would like more detailed logs just tell me how many -v's you need. 

[20200125_0739_mad.log](https://github.com/Map-A-Droid/MAD/files/4111987/20200125_0739_mad.log)
![Untitled](https://user-images.githubusercontent.com/57416363/73120656-4f118e80-3f47-11ea-96f8-2f1d790424b8.png)

**Comment by Expl0dingBanana** [comment]
Please test #715 and see if it works for you
