### ISSUE TITLE
MySQL integrity error on saving new walker

### ISSUE THREAD

**Issue by Tarlar2537** [Map-A-Droid/MAD#726]
After some time of running MAD an error occurs that the ajax request for saving a new walker fails for foreign keys violation. The log is attached:

https://pastebin.com/0xkm5Sc6

After restarting mad the problem seems to be solved but only for a while.

**Comment by Expl0dingBanana** [comment]
To replicate this issue:

- Create a new walker
- Edit the walker and add a new walker area
- Go back to walker page (either save on the walker or click walkers)
- Delete the walker
- Create a new walker - 500 occurs here

**Comment by Expl0dingBanana** [comment]
This has been merged to master.  Please re-open if you experience this issue.
