### ISSUE TITLE
File select dialog opens every time I visit localhost:5000/apk

### ISSUE THREAD

**Issue by fosJoddie** [Map-A-Droid/MAD#732]
Whenever I go to the APK wizard page, a "open file" dialog appears.

System: Windows 10
Browser: Chrome

**Comment by JimBim89** [comment]
Can confirm, glad I'm not alone with this.

**Comment by fosJoddie** [comment]
if I click this "reload" symbol on any line, the same happens:
![image](https://user-images.githubusercontent.com/5710881/73724261-37968a80-472b-11ea-87e7-41ca5e7fbce9.png)

It also happens if you click the cloud button to download an apk.

**Comment by fosJoddie** [comment]
bulk update also triggers the file dialog:
![image](https://user-images.githubusercontent.com/5710881/73724337-5d239400-472b-11ea-9281-71578f2a4627.png)
