### ISSUE TITLE
Cant Reach /settings/areas and /settings/walker with second instanze

### ISSUE THREAD

**Issue by spammer23** [Map-A-Droid/MAD#733]
Cant reach /settings/areas and /settings/walker when the second instace is running - all others sites are okay.
If i stop the other instance, and restart the primary, these sites work fine again.
Second instace: same folder, different config (only webhook enabled, madmin off, no devices connected)
Pull from 04.02.20 22:30
Log:
https://pastebin.com/ZkJVfTVF

**Comment by spammer23** [comment]
Not 100% sure if this relates to the second instance, but i have seen no other mentions in discord:

My Walkers ignoring some settings:
- Max Walker -> set it to 1, still both devices are running this area.
- Cords with endtime - Devices using the area after the endtime, a apply settings solves this

**Comment by spammer23** [comment]
Found a "Workaround", if I start both instances at the same time, everything seems okay.

**Comment by sn0opy** [comment]
Continuing in #902
