### ISSUE TITLE
Madmin won't start

### ISSUE THREAD

**Issue by KleinTobe** [Map-A-Droid/MAD#739]
A few days ago I created a new walker in Madmin with the corresponding areas. When I tried to save the Walker I got the following error message: 

https://hastebin.com/ajihuribed.sql

Since then the scans are running but Madmin can't be reached and nothing is sent with Webhook anymore. When I want to call Madmin I always get a 503 back as a message.

**Comment by sn0opy** [comment]
Did you try to restart MAD already?

**Comment by KleinTobe** [comment]
Yes, I restarted Madmin several times. There were no error messages during restart
