### ISSUE TITLE
weather_hook, Monocle schema, missing index/broken logic, 100% CPU usage.

### ISSUE THREAD

**Issue by JabLuszko** [Map-A-Droid/MAD#74]
Everything started after #7b88f2bff6626a736fa320747148fe06374c5d78 and chages to db/monocleWrapper.py

Before changes (with weather_hook enabled) query was:

```
 query_weather = (
             "INSERT INTO weather (s2_cell_id, `condition`, alert_severity, warn, day, updated) "
                number_of_rows = len(res)	            "VALUES (%s, %s, %s, %s, %s, %s) "
            "ON DUPLICATE KEY UPDATE `condition`=VALUES(`condition`), alert_severity=VALUES(alert_severity), "
            "warn=VALUES(warn), day=VALUES(day), updated=VALUES(updated)"
        )
```

which make sense - insert new row, on duplicate key update conditions.

However, if we look at "recommended" cleandb.sql 

```
CREATE TABLE `weather` (
  `id` int(11) NOT NULL,
  `s2_cell_id` bigint(20) DEFAULT NULL,
  `condition` tinyint(3) UNSIGNED DEFAULT NULL,
  `alert_severity` tinyint(3) UNSIGNED DEFAULT NULL,
  `warn` tinyint(1) DEFAULT NULL,
  `day` tinyint(3) UNSIGNED DEFAULT NULL,
  `updated` int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

ALTER TABLE `weather`
  ADD PRIMARY KEY (`id`);

ALTER TABLE `weather`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
```

The only key is id int(11) which is auto increment and not used in insert or update... [should be: s2_cell_id] - so with that kind of query every time MAD receives weather info from client it will **INSERT** new row. So after not even a month of running my stats are:

```
mysql> select count(*) from weather;
+----------+
| count(*) |
+----------+
|   175486 |
+----------+

mysql> select COUNT(DISTINCT(`s2_cell_id`)) from weather;
+-------------------------------+
| COUNT(DISTINCT(`s2_cell_id`)) |
+-------------------------------+
|                             7 |
+-------------------------------+
1 row in set (0.07 sec)
```

I haven't really checked what the code by @cecpk is supposed to do, but it hammers my CPU to almost death (db on same server as MAD) and the whole refactor was probably not needed - all we need is index/key on s2_cell_id?

No idea how it goes with 2nd schema - never used, never tested, please double check.

I just run ```DELETE FROM `weather`;``` and I hope current code will handle duplicates, will report later.

EDIT: Yep, current code handles duplicates, only one entry per s2_cell_id and no cpu ⚒

**Comment by cecpk** [comment]
Already fixed. Add a table truncate in next version
