### ISSUE TITLE
Quest Worker not clearing inventory

### ISSUE THREAD

**Issue by Christian-X** [Map-A-Droid/MAD#746]
Sometimes (seen it a few times now) the following happens:

This worker tries to spin a stop, can't, because of inventory is full, and will never suceed to empty its inventory.

https://pastebin.com/d6qSvWs5

as far as i can tell by experimenting, when it arrives in this state, you can't assign it to a new walker anymore, as it's stuck in this "unprocessed event" + "can't do that" loop.

(mad restart helps)

**Comment by crhbetz** [comment]
This is among the things I want to fix in #741 .
If you happen to see it again, could you confirm that restarting pogo (you can do it manually through MADmin - devicecontrol) fixes the issue too?

**Comment by Christian-X** [comment]
I'll try when it happens again.
