### ISSUE TITLE
encounter_id get over the limit of BIGINT

### ISSUE THREAD

**Issue by Micha854** [Map-A-Droid/MAD#754]
found an issue to get over the limit of BIGINT (max 9223372036854775807 (63 bits)) of the pokemon table

i have an encounter_id "12231755850854333585" that over the limit

the type_id of table "trs_stats_detect_raw" have an type VARCHAR(100)

i think a change from type BIGINT (20) from pokemon.encounter_id to VARCHAR (100) could solve the problem

In addition, adjustments to the shiny stats page have to be made accordingly

**Comment by sn0opy** [comment]
It just needs to be changed to an unsigned bigint which holds 20-digit values just fine.

**Comment by Micha854** [comment]
BIGINT(20) UNSIGNED is okay but the type_id on trs_stats_detect_raw table is VARCHAR(100)

so is type_id = encounter_id

that doesn't make sense to me and should be adjusted

**Comment by sn0opy** [comment]
Well, the reason why `trs_stats_detect_raw.type_id` is a VARCHAR is because it actually holds numbers and strings. Hence we cannot simply change it and beside of proper indexing, there's also no reason to
