### ISSUE TITLE
Data is suddenly not send to webhooks any more (thread crashed probably)

### ISSUE THREAD

**Issue by gcm-explo1t** [Map-A-Droid/MAD#772]
In the current version: 7c2792d01a99143b46f8d23c8ea4fa4c80d6a90f
The Raids etc. are only send a few times to the configured webhooks and then they suddenly stop.

Verbose logs can be provided, just message me.

**Comment by sn0opy** [comment]
Unfortunately, this does not help at all. Check your logs for errors. That commit also has 100% nothing to do with anything related to webhook sending. Please use Discord to ask for support. If there's an actual bug, feel free to reopen this issue.
