### ISSUE TITLE
IV_MITM needs min_time_left_seconds>0 to start working

### ISSUE THREAD

**Issue by cyphercris** [Map-A-Droid/MAD#773]
I try to run iv_mitm, but finally start working when min_time_left_seconds>0. Needs to fix that or put proper info at area settings.
I get this warring at logs when min_time_left_seconds = 0 or empty
> [03-14 18:01:42.06] [prio_queue_update_cd_iv] [          DbWrapper:372 ] [ WARNING] DbWrapper::get_to_be_encountered: Not returning any encounters since no time left or eligible mon IDs specified
[03-14 18:01:42.06] [MainProcess|samsung] [   RouteManagerBase:857 ] [    INFO] Not updating routepools in iv_mitm mode

**Comment by crhbetz** [comment]
I agree the description could be a little clearer, and defaulting to `None` which basically disables the mode doesn't make much sense.

However I can't see in the code that `min_time_left_seconds = 0` would be an issue. Are you 100% sure about this?
You can't get the `WARNING` output you provided with the value 0, this only can appear when you leave the field empty. Did you properly apply settings when trying 0?

**Comment by cyphercris** [comment]
I try many settings combination and this works when change to non zero value. Can check again but it should be easy to check.

**Comment by cyphercris** [comment]
Strange, test now all working good. Some days ago start working when I change it to value higher than 0. I try apply settings, reboot mad and nothing help. Really try many combinations. So close now the issue, maybe problem not happen again.
