### ISSUE TITLE
Madmin : Add a "Restart all failed Job" button

### ISSUE THREAD

**Issue by bbdoc** [Map-A-Droid/MAD#798]
Could we have a "restart all failed job" button in madmin ?

When updating nearly 100 devices and 15-20 are failing, it's not always easy to restart all failed ones one by one (even worse when speaking about ROM update as it's 2 jobs each). A button to restart all failed jobs would really be nice.

Thanks

**Comment by Expl0dingBanana** [comment]
Duplicate of #854
