### ISSUE TITLE
Docker builds for master  and dev branch with incrementing tags

### ISSUE THREAD

**Issue by Breee** [Map-A-Droid/MAD#808]
# Docker Builds

Currently you have only one build available on dockerhub: 
https://hub.docker.com/r/mapadroid/map-a-droid/ 

tagged as **latest**

I'd suggest to build images for the dev + master branch and Tag them. 

## Why? 
People that automatically update and deploy their services can come into trouble. 
- It can happen that a build is unstable, so we need have the possibility to pull an older image.

## Tags
- For master, I'd tag every build with the current **build-iteration or commit-hash** and the tag **latest**
- For dev i'd just just use a tag **dev**

## Which CI pipeline?
- I suggest CircleCi or the new Github actions. Github actions even offer good templates for docker builds + pushs to dockerhub.

It's basically no work and it has a big payoff.
I can assist you, if you need help.

**Comment by clburlison** [comment]
It's also basically no work to do a git pull and build locally. IMO if the core developers aren't using this workflow it should be supported by the community.

**Comment by Breee** [comment]
Agree, I just thought it's nice to have it all in one place ;)
But fair enough, I can setup a mirror repo and a CI pipeline that pushes images to my dockerhub and reference to them in the Wiki.
