### ISSUE TITLE
Worker doesn't quit quest mode when it's out of scheduled time

### ISSUE THREAD

**Issue by kamieniarz** [Map-A-Droid/MAD#810]
It's a second time during last 3 days - all my quests are set to coords and should be done by 8:00. 2 days ago one of my workers was still doing quest at 11am, today another worker was stuck at 10am. I had to reboot these devices to load them up properly

**Comment by cyphercris** [comment]
+1 I also noticed that its some problems after quest scan.

**Comment by muckelba** [comment]
Can you try to grab a debug log from that?

**Comment by kamieniarz** [comment]
Seems to be fixed
