### ISSUE TITLE
Commit ac8a4c4 fixed check_time_period (#812) - causes less mon scanning

### ISSUE THREAD

**Issue by cyphercris** [Map-A-Droid/MAD#816]
Less mon is scanning. Revert  this commit #812  and its looks all is ok.  
![unknown](https://user-images.githubusercontent.com/16975350/79860962-e31eb500-83d3-11ea-94f8-0ca360843686.png)

**Comment by JabLuszko** [comment]
#812 touches only Walker scheduling... so if there is any issue it's something more than *less* mons getting scanned. More like walkers not joining areas or something. Get your MAD logs, show your walker settings.

**Comment by cecpk** [comment]
Need your walker settings - thx

**Comment by kamieniarz** [comment]
I see 3 options to fix your issue:
1. Make bigger geofence - probably less IV mons, worse scan times but generally more mons
2. Buy a new device - win-win situation (but requires financial input)
3. 3 mons per jump - tripple win-win situation with almost no effort 😎

**Comment by cyphercris** [comment]
@cecpk what data you need
![image](https://user-images.githubusercontent.com/16975350/79863789-a43f2e00-83d8-11ea-8d6b-dad67e2bf4d4.png)
mon_standard - mitm_mon, prioq, strave route enabled, quest - quest,

**Comment by cecpk** [comment]
Delete first line
Change last line: 1:30-1:00

**Comment by cyphercris** [comment]
I change and let you know. When all previous are are time closed its looks working normal. I have second walker with quest event and no drops mon
![image](https://user-images.githubusercontent.com/16975350/79872793-85e02f00-83e6-11ea-8054-1be9a537c878.png)

**Comment by cyphercris** [comment]
With new PD problem gone
