### ISSUE TITLE
RGC won't reconnect to MAD untill pressing Stop&Start or reboot the device

### ISSUE THREAD

**Issue by kamieniarz** [Map-A-Droid/MAD#864]
This issue is not a new thing and I'm definitely not the only one experiencing it but I (finally) decided to mention this issue on Discord and finally here.

I have a RGC feature request - from time to time RGC kinda dies after mad restart/crash/whatever or vps crash or when device (mostly phones) drops wifi connection for a while. In this scenario when you open RGC it says it's running but it's not - it's not and won't register in mad instance until you fix this RGC lag or however to call it. Fix is easy: stop&start RGC or reboot device. But sometimes it's not possible to do so remotely - eg no adb, no teamwiever/scrcpy or just no time lol. 

My request here is to add such a function (stop&start or reboot) to RGC so it could do what's necessary without connecting to MAD instance. I belive there could be a switch in RGC to activate such function and some kind of time trigger (default 10min?) or sth after which RGC would restart itself or just reboot device if fail to... not sure what: connect to MAD (if that's the issue with RGC crashes?), assign to walker or just sth else that is pretty self explaining in that case - that's basically up to what's crashing RGC forcing us to restart it

**Comment by sn0opy** [comment]
We need adb logs for this.

**Comment by cyphercris** [comment]
Today I have internet down and after back rgc not connected again, but device (phone) works. Try to send logs if can recreate situation.

**Comment by kamieniarz** [comment]
This happened to me again with all 47 devices I have - my server lagged out in a weird way so I had to do a soft reboot of the whole vps. After that I launched mad which was full of GMO reveiced logs but none of the devices connected to MAD untill I rebooted them. So looks like RGC connection from before vps restart wasn't closed on devices' side untill I rebooted them. Unfortunately I can't provide adb logs

**Comment by sn0opy** [comment]
No logs, no fix...

But as you've been reporting the exact same issue with your iPhones, you probably want to start to look into your obviously broken server or network setup...

**Comment by kamieniarz** [comment]
When did I report such thing with iPhones? They're running just perfect what I'd love to say about MAD and Android devices but I can't 🤷‍♂️

But still my request here is to add an option to RGC to auto-reboot device when connection was dropper or wasn't successful. This request is mostly motivated by the fact I'm not able to get logs or reproduce this issue on purpose. It's a rare thing but annoying

**Comment by Expl0dingBanana** [comment]
This occurred today when I power cycled my ATV setup and have sent the logs off.

**Comment by kamieniarz** [comment]
Seems to be fixed
