### ISSUE TITLE
Add better documentation and link at new quest enhancement variables

### ISSUE THREAD

**Issue by gcm-explo1t** [Map-A-Droid/MAD#882]
The explanation for the variable "enhanced_mode_quest_safe_items" is yet not very understandable: Undeletable items for enhanced quest mode (Default: 1301, 1401,1402, 1403, 1106, 901, 902, 903, 501, 502, 503, 504, 301)

Better would be:
Undeletable items from the inventory for enhanced quest mode [Link](https://github.com/Furtif/POGOProtos/blob/master/src/POGOProtos/Inventory/Item/ItemId.proto) (Default: 1301, 1401,1402, 1403, 1106, 901, 902, 903, 501, 502, 503, 504, 301)

**Comment by JabLuszko** [comment]
If you click the box to add/edit something you will be presented with nice name<->id list. Totally not needed to link to outdated repo.

![image](https://user-images.githubusercontent.com/1145742/83244787-1a853c00-a1a0-11ea-95e5-1ce96902a807.png)
