### ISSUE TITLE
Drastic decrease of IV mons in 1.4.x.x PogoDroid versions

### ISSUE THREAD

**Issue by kamieniarz** [Map-A-Droid/MAD#893]
Since well known GMO issues my scans effectiveness decreased due to reboots caused by timeouts. But after all PD 1.3.3.10 worked pretty well. 

My issue is related with PD 1.4.x.x - as far as I remember I tried 3 versions, including the latest one. In all of them GMO issue seems to be fixed but I've noticed decrease of mons, raids and drastic decrease of IV mons. Red line is when I updated PD from 1.3.3.10 to 1.4.1.5:
![Bez tytułu](https://user-images.githubusercontent.com/9063907/84270586-363afb80-ab2b-11ea-9dab-c00e71048aae.png)

I've noticed exactly the same thing on each 1.4.x.x PD version I've tested. Also over a half of IV mons from grafana is from my RDM devices, so looks like MAD (or actually PD) causes decreased IV scans by 90%... I thought that maybe it's raw port issue in latest PD versions but it's not - madmin mon stats also look as bad as grafana stats.

This issue doesn't seem to affect android phones tho, I have issues with all X96mini I own.

I checked MAD logs - nothing special there. I tried 1.3.3.10 and 1.4.x.x with pogo 0.175.2, 0.175.3 and 0.177.0 - no changes

PS my VPS cpu usage also significantly decreased so looks like PD has issue with grabbing data. MAYBE it's pogo related but still difference between 1.3.3.10 and 1.4.x.x versions is huge

**Comment by kamieniarz** [comment]
Due to my unawareness atvs autoupdated PD from `1.3.3.10` to `1.4.1.5` due to reboots caused by GMO issues and as you can see there was a decrease of IV scans and what's new - Quests are a mess with new PD too...
![Bez tytułu](https://user-images.githubusercontent.com/9063907/84369152-b7030180-abd6-11ea-9e59-34f4aee7efda.png)

**Comment by ChaosEmpire** [comment]
same here, with 1.4.1.5 from yesterday 
decrease of pokemon ~20%
quest have been slower too

**Comment by krzee** [comment]
i upgraded PD to 1.4.1.3 (internal test release) before pogo was force updated to 177, and i actually had a big increase in spawns, then 177 was forced and i updated pogo, then i got the same drop you guys are talking about.
try to remember that niantic routinely screws things up and effects us

**Comment by kamieniarz** [comment]
> try to remember that niantic routinely screws things up and effects us
Sure, that makes sense but it's not like it's on niantic's side too especially when `1.3.3.10` works but `1.3.3.13` and other versions till `1.4.1.5` don't work

**Comment by krzee** [comment]
i guess i can try 1.3.3.10 again, but i got my increase of spawns (on old pogo version) when i went from 1.3.3.10 to 1.4.1.3 (which im still on). and then it went back down when i updated pogo to 177 while not touching pogodroid

**Comment by ChaosEmpire** [comment]
i m on 177 since first day, same for 177.1
during 2 hours today i reached regular amount of pokemon, but in both cases i missed lot iv scans

**Comment by kamieniarz** [comment]
And obviously same issue with 1.5.0.3 version

**Comment by cecpk** [comment]
Im closing this. Reports based on personal feelings without any mad logs and/or logcats from devices doesn’t help anybody here. Open a new issue with stuff helping us to understand the problem. Thanks.

**Comment by kamieniarz** [comment]
These are not personal feelings but real issues and since I'm unable to grab logs right now so I'm hoping anyone else could do that. I did everything I could to point out where the issue is. **Ignoring the issue like you do now won't help fixing it**

**Comment by cecpk** [comment]
Im not fixing it, because there is nothing to fix ...

**Comment by kamieniarz** [comment]
You're beeing a joke right now

**Comment by kamieniarz** [comment]
@sn0opy accused my on discord for posting 3rd party stats instead of madmin: here you go
![Bez tytułu](https://user-images.githubusercontent.com/9063907/86536033-caa73c80-bee4-11ea-8afc-955fe08e1de6.png)
First hour is after updating pd from 1.3.3.10 to 1.5.0.3, second hour is after going back to previous version and last hour is ongoing. As you can see madmin stats are as bad as grafana stats. Here you have grafana stats:
![Bez tytułu](https://user-images.githubusercontent.com/9063907/86536078-1659e600-bee5-11ea-8927-01d9782ec163.png)

**Comment by sn0opy** [comment]
As said on Discord, if anyone reads this: we keep this closed until someone is actually able to post device/adb logs for this issue.
