### ISSUE TITLE
log_level is not working 

### ISSUE THREAD

**Issue by muckelba** [Map-A-Droid/MAD#916]
MAD has the option to define log levels via config.ini instead of using -v[vvvvv]. But this option does not to be working right now. I could imagine that the logging rework has something to do with that.

**Comment by Expl0dingBanana** [comment]
We are only displaying the first character in the level.  Rather than showing DEBUG2 - DEBUG5 it will just show D which is the same as the .debug statement.  Is this the issue you are seeing?

**Comment by muckelba** [comment]
Oh okay. I went over the settings.ini again and tried `log_level:  DEBUG1` instead of `log_level:  1` (which i tried earlier) and it works. So it was just a layer 8 problem :D But maybe the config description can be adjusted to be more clear. Or a warning on MAD startup that an invalid value was entered.
