### ISSUE TITLE
Faster shiny data

### ISSUE THREAD

**Issue by kamigusai** [Map-A-Droid/MAD#925]
Can someone query "is_shiny" to the "pokemon" table? We have stuff like costume, form... why not shiny stat aswell?

If that was possible we would not have to wait for the "trs_stats_detect_mon_raw" table to be updated (which takes minutes out of the encounter spawn) to get a notification for a shiny. It could add up to 5 minutes to a shiny spawn for those who like to catch them...

Another solution would be updating "trs_stats_detect_mon_raw" table as regularly as "pokemon" table but maybe that would cause issues like someone have mentioned on discord.

Personally I would be very grateful if someone could implement that :)

**Comment by ChaosEmpire** [comment]
without corresponding device you wont know which account to use...
if the info get written later, you still have to wait for it...

**Comment by kamigusai** [comment]
> 
> 
> without corresponding device you wont know which account to use...
> if the info get written later, you still have to wait for it...

Yeah true. I didn't even thought about that because I'm only playing with one device. What if "worker" is added aswell?

Still, why is it written later? Could it be faster? I just don't quite understand when I check that an encounter was shiny and it only appears on MADmin minutes later. Feels like "trs_stats_detect_mon_raw" gets later data everytime.

**Comment by sn0opy** [comment]
Multiple workers can see the same mon. It makes no sense to add it to the mon table. 

You can enable raw stats in the config to store that info. It's even displayed in MADmin and there's a 3rd party tool called Shiny watcher which posts shinies to Discord. Check the 3rd party channel in Discord

**Comment by kamigusai** [comment]
> You can enable raw stats in the config to store that info. It's even displayed in MADmin and there's a 3rd party tool called Shiny watcher which posts shinies to Discord. Check the 3rd party channel in Discord

Yeah I know, I use it. The problem I'm facing is that shiny stats (trs_stats_detect_mon_raw) only get to the database every 5 minutes 
![image](https://user-images.githubusercontent.com/67837834/86519593-033b0d80-be34-11ea-88e7-29410c913ea0.png)

And this can take up to 5 minutes of the spawn time. Can't it be updated every 10 seconds like the "pokemon" table?

**Comment by Expl0dingBanana** [comment]
Save time was implemented with -gsst

**Comment by krzee** [comment]
This may be a good place to point out that mad isnt developed for botting. The shiny data was added for stats and people work off that data to bot their shinies, but that's not really the goal of mad, at least not last i heard.

**Comment by Expl0dingBanana** [comment]
Going to close this as it was implemented / unsure this is within the scope of the project.
