### ISSUE TITLE
Quests MITM stuck at GPS signal Error

### ISSUE THREAD

**Issue by bbdoc** [Map-A-Droid/MAD#93]
Adding this one here for reference.

When using mock locations, it's quite normal to have an Error 11 on pogo startup. It usually resolves when start.py start to send geofix.

Issue is that when using quests scan, it will detect the Error 11 : 

`[    WorkerBase][ WARNING] _check_pogo_main_screen: GPS signal error`

and after 5 errors in a row it will restart pogo : 

`[    WorkerBase][   ERROR] _check_pogo_main_screen: Red error multiple times in a row, restarting`

but as far as it will never send any geofix, it will remain stuck in a reboot loop forever.

Solution would be to send a geofix when GPS signal error is detected so that it resolves itself and quest worker can continue its normal work.

**Comment by pkiel** [comment]
Same problem with mock and without.
Only way to fix it is to force-stop RGC and start over. Sometimes restart of the device does help but not everytime.

Maybe it is possible that RGC can kill itself?

If GPS error:
    device = force-stop RGC + sleep 10 + start RGC

**Comment by fosJoddie** [comment]
just FYI:

when pogo opens, drag the notification screen down to hide the GPS not found error.
pogo will now not restart because of "gps not found" and quest scanning will continue

**Comment by bbdoc** [comment]
@fosJoddie Thanks but I'm scanning quests between 00:15 and 7:00, and usually sleeping at that time. Yesterday it went fine for 1 hour and then failed on this message.

**Comment by fosJoddie** [comment]
yeah, was more to put it up here for anyone wanting a temporary workaround for waking hours 👼  

I'm thinking we just need to relax the gps not found thing by forcing some location updates before restarting

**Comment by pkiel** [comment]
I was able to reproduce the error:
- Close Pogo
- From recent apps switch to RGC
- Click Stop
- Click Start
- Start Pogo from homescreen
=> Error 11 (GPS not found)


Very dirty workaround:
Replace https://github.com/Map-A-Droid/MAD/blob/master/worker/WorkerBase.py#L536 with:

```
                self._communicator.startApp("de.grennith.rgc.remotegpscontroller")
                time.sleep(10)
                self._communicator.setLocation(0, 0, 0)
                time.sleep(10)
                self._reboot()
```

Tested this over two hours with two phones and this was the only way to get the quest-worker running again after GPS error.
Will test it the whole night and see the result in ~7 hours.
