### ISSUE TITLE
Broken quests scanning

### ISSUE THREAD

**Issue by kamieniarz** [Map-A-Droid/MAD#936]
This issue is present in latest pogodroid. Basically there are 2 issues.

**Issue 1**: when MAD opens menu it closes it before clicking on inventory icon so in fact clearing box doesn't work cause MAD clicks game map instead of inventory icon. Logs from below are within timeframe when it all happened.
MAD debug logs:
[logs1.txt](https://github.com/Map-A-Droid/MAD/files/4962902/logs1.txt)
Logcat:
[logcat1.txt](https://github.com/Map-A-Droid/MAD/files/4962905/logcat1.txt)

**Issue 2**: sometimes MAD manages to enter items tab but it simply errors out after deleting 1, 2 or 3 types of items. Example: it deletes all Poke balls (clicks trashcan, clicks `+` and deletes them) but instead of clicking on trashcan of Great ball it just exits from items menu leaving error in logs. After that MAD continues spinning stops.
MAD debug logs:
[logs2.txt](https://github.com/Map-A-Droid/MAD/files/4962909/logs2.txt)
Logcat:
[logcat2.txt](https://github.com/Map-A-Droid/MAD/files/4962912/logcat2.txt)

All of my 44 X96mini atvs are affected by this issue. It wasn't present in my last PD version 1.3.3.10. Literally everything is up-to-date (mad, rgc, pd, pogo, atv rom). I tried reinstalling tesseract - no luck.
Due to this issue my atvs manage to finish like 20-30% quests in 6h instead of 100% in 4-5h... 
It's already over a week since I have this issue so I hope it'll be fixed soon

**Comment by sn0opy** [comment]
Regarding issue 2: we need new logs here. Your MAD is modified and not the actual master code. Your WorkerQuests.py like 875 probably looks like this right now: `if proto_to_wait_for in [101, 104, 4]:`. But it must look like this: `if proto_to_wait_for in [101, 104]:`. Please re-do the test and post logs of the problem.

The logcat and mad logs both show the location of a tap. It would be really helpful to have an actual real screenshot of the device at that exact time to validate it is actually clicking at the right place on your device.

By the general looks of it: your device does not actually delete items right now. type=4 protos are inventory deltas which should contain deleted items. But they're always empty for your.

**Comment by kamieniarz** [comment]
Damn I totally forgot about it - adding `4` was ment to fix timeouts and it kinda did. Anyway both issues from above showed same bahaviour even without this modification. I'll do some tests with new PD (and clean MAD) and let you know how it goes

**Comment by kamieniarz** [comment]
Got new logs. Device managed to enter items page with no issues but still aborted deleting them. It deleted 1 potion and almost all Poke Balls - then it just quit items page and started doing quests again.
MAD debug logs:
[logs1.txt](https://github.com/Map-A-Droid/MAD/files/4967178/logs1.txt)
Logcat:
[logcat1.txt](https://github.com/Map-A-Droid/MAD/files/4967180/logcat1.txt)

I'm still testing new PD so I'll be probably back with more logs if you need them

**Comment by sn0opy** [comment]
Well, still the same issue. Either it doesn't properly delete the items (sometimes), or the game simply doesn't report back the change. MAD's logic does seem to be correct here by the looks of it.

You could try to set this variable to 60 or even 90 seconds to see if that somehow helps to fix the issue completely

https://github.com/Map-A-Droid/MAD/blob/master/mapadroid/worker/WorkerQuests.py#L550

**Comment by kamieniarz** [comment]
It didn't help :/ Even made it slower

**Comment by sn0opy** [comment]
> It didn't help :/ Even made it slower

Weall yeah, ofc it became slower. with the change mentioned above, you raised the timeout to wait for the data. Instead of waiting 35s, it's now waiting 60 or 90 seconds depending on what you set.

I guess we need either a full res video + adb log and MAD log to match the logs + click coordinates with the screen or screenshots of at least the part where it errors out.

I really don't know why the game doesn't receive the inventory delta in your case.

**Comment by kamieniarz** [comment]
Seems like issue "got fixed" cause today finally after 10 days I had scanned all Quests. I'm not sure what fixed it tho cause yesterday I updated all devices to the newest PD and also I changed VPS 🤷‍♂️ Anyway I'm closing this, thanks for help
