### ISSUE TITLE
FR: Use List of items to delete for both quest modes

### ISSUE THREAD

**Issue by ChaosEmpire** [Map-A-Droid/MAD#942]
Currently we have a list of items, which shall be not deleted during questing 
regular quest mode, hardcoded in mad code
payed quest mode configurable list in madmin

FR: 
Use configurable itemlist for both quest modes general/payed

**Comment by JabLuszko** [comment]
No, because normal mode uses OCR and it's not reliable, it can still delete items you will have on the list and then people will complain even more.

**Comment by cecpk** [comment]
List is only for Addons.
