### ISSUE TITLE
autoconfig_improvements autogen of autoconf.txt

### ISSUE THREAD

**Issue by Christian-X** [Map-A-Droid/MAD#955]
The automatically generated file can't work - 
It adds the RGC endpoint, not the pogodroid endpoint.

**Comment by Expl0dingBanana** [comment]
Ya I noticed that last night after pushing. Will get it fixed today

**Comment by Expl0dingBanana** [comment]
This has been resolves with commit 1b7aa1cbf1ef4b4d036a4c85b1975e6ea7e91230.
