### ISSUE TITLE
Set this open?

### ISSUE THREAD

**Issue by reedy** [Map-A-Droid/MAD#957]
`Set this open True, if you scan the area for gyms / spawnpoints the first time`

Is `open` supposed to be `option`?

<img width="602" alt="Screenshot 2020-08-16 at 17 23 21" src="https://user-images.githubusercontent.com/67615/90338952-394bdf80-dfe5-11ea-8a84-24edb9e3fab5.png">

**Comment by sn0opy** [comment]
Fixed in f064ed6bd471f9286c706becc379ba53f75e0543
