### ISSUE TITLE
Retry option for raw and serialized POST in PogoDroid

### ISSUE THREAD

**Issue by kamieniarz** [Map-A-Droid/MAD#961]
**Feature request.** As you may know PogoDroid doesn't retry serialized or raw POST - if there's a timeout data is lost.
```
ProtoHookJ: Exception while POSTing data (serialized): java.net.SocketTimeoutException: timeout
```
```
ProtoHookJ: Exception while POSTing data (raw): java.net.SocketTimeoutException: connect timed out
```

What's the reason for that? Data loss is is obviously not what we want so this feature could help fighting smaller or bigger issues with POSTing data which might be caused by many factors. Serialized post timeout data causes MAD to retry action which makes it less efficient. Raw post timeout is worse here cause if anyone uses RDM also or simply a second db data is lost without an option to retry to fetch them again like with serialized.

**Comment by Grennith** [comment]
There already is a retry in place (3 attempts are made).
https://square.github.io/okhttp/4.x/okhttp/okhttp3/-ok-http-client/-builder/connect-timeout/

**Comment by sn0opy** [comment]
So, is this still an issue especially with @Grennith mentioning there's alreasdy a timeout in place?
