### ISSUE TITLE
Form ID id 0 on outgoing raid webhooks for some pokemon

### ISSUE THREAD

**Issue by Artanicus** [Map-A-Droid/MAD#989]
MAD revision 941f8d3acf (current HEAD)

Based on raids found today the following are receiving 0 as a form id:
```
134
403
485
501
532
```
As far as I can see these all have expected form IDs, for example 485 is supposed to be 1862.

Whereas these receive a non-zero form:
```
105
26
27
3
6
68
9
95
99
```

**Comment by Artanicus** [comment]
```
MariaDB [mad]> SELECT pokemon_id, form FROM `raid` WHERE start > 2020-09-03 GROUP BY pokemon_id, form ORDER BY pokemon_id;
+------------+------+
| pokemon_id | form |
+------------+------+
|       NULL | NULL |
|          3 |  169 |
|          6 |  178 |
|          9 |  187 |
|         26 |   50 |
|         27 |   51 |
|         37 |   56 |
|         62 |  241 |
|         95 |  902 |
|         99 |  873 |
|        105 |   79 |
|        105 |   80 |
|        121 |    0 |
|        131 |  322 |
|        134 |    0 |
|        160 |    0 |
|        215 |  797 |
|        226 |    0 |
|        342 |    0 |
|        362 |    0 |
|        457 |    0 |
|        460 |  935 |
|        485 |    0 |
|        501 |    0 |
|        532 |    0 |
|        535 |    0 |
|        599 |    0 |
|        613 |    0 |
|        645 |  144 |
+------------+------+

```

**Comment by sn0opy** [comment]
Well, these forms are coming from the game.

PD is grabbing the forms as is without converting them in anyway. It's just an integer value that is being grabbed from PD, serialized to JSON, sent to MAD and MAD is grabbing the exact same integer value without modyfing it and adds it to the DB.

It's not the first time a form value is not "correct" or according to the form enum.

**Comment by JabLuszko** [comment]
To extend what sn0opy said - because something exists in Form Enums (or there is image in-game) it does not mean that Niantic is using it. The usual morph from "MONNAME" to "MONNAME_NORMAL" mostly happens when the "MONNAME_SHADOW" is actually released in-game and you can somehow obtain it - if not, they tend to use "MONNAME" and 0(0) as form.

**Comment by Artanicus** [comment]
That makes sense, thanks for the thorough explanation.
