### ISSUE TITLE
PD always shown to have an update on MAD Packages

### ISSUE THREAD

**Issue by reedy** [Map-A-Droid/MAD#997]
<img width="1136" alt="Screenshot 2020-09-11 at 15 14 59" src="https://user-images.githubusercontent.com/67615/92941470-4f17bd80-f448-11ea-899f-930a1d701462.png">

It seems that pd always seemingly shows the "download newer version" against PD button even after you've clicked it/update everything.

Same if you delete it and download it again.

@krzee confirmed the same behaviour on discord

**Comment by reedy** [comment]
Looks like this might have been fixed recently

**Comment by crhbetz** [comment]
Yes, another thing I did in #1081 - forgot to list it and didn't go through issues I might be fixing 😅

**Comment by reedy** [comment]
Sweet. Thanks! :)
